# FROM nginx:alpine

# COPY nginx.conf /etc/nginx/conf.d/nginx.conf
# COPY mime.types /etc/nginx/mime.types
# EXPOSE 80

FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf

##COPY default.conf /etc/nginx/conf.d/default.conf