# learn_probabilities_threaded.py
# Author: Joshua Elston, Mahima Ganni
# Last Edited: 09/01/2026

# This script is used to create simulation runs of the IHab/HALO Gateway
# environment using the Biosim configuration files generated by TRACLabs.
# With the reduced subset of anomaly scenarios being modeled, the script
# then looks to perform parameter learning to inform the probabilities
# within the Bayesian network CPDs.

# Updated anomaly list to include relevant subgroups and "Unknown Anomaly", and updated anomalies
# with symptoms in both modules to measure whether the hatch between the modules is open (1, True)
# or closed (False, 0)
# Supports running multiple config files in a given run
# Parameter learning mechanism updated to Bayesian Estimation using Dirichlet priors
# (seeking to resolve uniform distributions issue observed using Expectation Maximization)
# Able to perform parameter learning in parallel to reduce training time
# Updated to only perform parameter learning on a subset of the nodes in the network (excluding
# group-level and unknown anomaly nodes, which are predefined and deterministic)
# Also updated 'Hatch Status' to more accurately-defined 'Fan Status' (1='on', 0='off'), that is
# now a parent of module-specific parameters

# Updated on 07/09/2026 to reflect changes to group names and run with connections between parameters
# and group (now subsystem) nodes
# Updated on 08/26/2026 to reflect new updates to subsystem/anomaly/hidden node names
# Updated on 09/01/2026 to finalize changes to new anomaly scenario architecture

# Usage:
#   python learn_probabilities_threaded.py # default: 4 workers, 1000 ticks
#   python learn_probabilities_threaded.py --workers 14 --ticks 500 
#   python learn_probabilities_threaded.py --testing # run full testing across different threads and ticks

import os, json, subprocess, requests, time, argparse, sys
import pandas as pd
from collections import defaultdict, deque
from concurrent.futures import ThreadPoolExecutor, as_completed
import threading
from math import prod
import pickle
import numpy as np

from pgmpy.models import BayesianNetwork

current_dir = os.path.dirname(os.path.abspath(__file__))

# Add the Gateway directory (one level up) to the Python path
gateway_dir = os.path.abspath(os.path.join(current_dir, '..'))
if gateway_dir not in sys.path:
    sys.path.insert(0, gateway_dir)

_mars_repos_dir = os.path.abspath(os.path.join(current_dir, '..', '..', '..', '..', '..', '..', '..'))
CONFIG_DIR = os.path.abspath(os.path.join(current_dir, 'configuration'))

from reduced_network_structure import reduced_network
from reduced_known_probabilities import known_cpds

reduced_split_probability_dict_path = os.path.join(gateway_dir, "reduced_split_probabilities_dict.json")
reduced_hidden_probabilities_dict_path = os.path.join(gateway_dir, "reduced_hidden_probabilities_dict.json")
with open(reduced_split_probability_dict_path, "r") as file:
    reduced_split_probability_dict = json.load(file)
with open(reduced_hidden_probabilities_dict_path, "r") as file:
    reduced_hidden_probabilities_dict = json.load(file)

# Create the Bayesian Network
model = BayesianNetwork(reduced_network)

SERVER_URL = 'http://localhost:8009'

# Lock to serialize simulation start requests 
_start_lock = threading.Lock()

CONFIG_ANOMALY_MAP = {
    'oga.biosim':    {'anomaly': 'OGA Failure',   'fan_status': 'on', 'tick': 200},
    'oga_ihab.biosim': {'anomaly': 'OGA Failure',  'fan_status': 'off',   'tick': 100},
    'vccr_pfs.biosim':    {'anomaly': 'VCCR Particulate Filter Saturation', 'fan_status': 'on', 'tick': 200},
    'vccr_sbs_ihab.biosim': {'anomaly': 'VCCR Sorbent Bed Saturation', 'fan_status': 'off', 'tick': 200},
    'vccr_sbs.biosim':      {'anomaly': 'VCCR Sorbent Bed Saturation', 'tick': 200},
    'decompression_ihab.biosim':   {'anomaly': 'Module Decompression (IHab)',  'tick': 0},
    'decompression_halo.biosim':   {'anomaly': 'Module Decompression (HALO)',  'tick': 0},
    'decompression.biosim': {'anomaly': 'Module Decompression (IHab)', 'second_anomaly': 'Module Decompression (HALO)', 'tick': 0},
    'o2_delivery_ihab.biosim':   {'anomaly': 'O2 Delivery System Malfunction (IHab)', 'fan_status': 'off', 'tick': 100},
    'o2_delivery_halo.biosim':   {'anomaly': 'O2 Delivery System Malfunction (HALO)', 'fan_status': 'off', 'tick': 100},
    'o2_delivery.biosim':        {'anomaly': 'O2 Delivery System Malfunction (IHab)', 'second_anomaly': 'O2 Delivery System Malfunction (HALO)', 'tick': 100},
    'high_humidity.biosim': {'anomaly': 'Unknown Anomaly', 'tick': 200},
    'low_humidity.biosim':  {'anomaly': 'Unknown Anomaly', 'tick': 0},
    'high_o2.biosim':       {'anomaly': 'Unknown Anomaly', 'tick': 150},
    'low_co2.biosim':       {'anomaly': 'Unknown Anomaly', 'tick': 0},
    'high_pressure.biosim': {'anomaly': 'Unknown Anomaly', 'tick': 125},
}

# NOTE: NEW CODE ON 09/16/2026
SENSOR_LOCATIONS = ["IHab", "HALO"]
SENSOR_LEVELS = ["high", "low"]
ALL_SENSOR_PARAMS = ["ppO2", "ppCO2", "Humidity", "Total_Cabin_Pressure"]

def _sensor_names(param):
    """All high/low × IHab/HALO column names for a given measured parameter."""
    return [f"{level} {param}_{loc} ({loc})" for level in SENSOR_LEVELS for loc in SENSOR_LOCATIONS]

ALL_SENSOR_NAMES = [s for param in ALL_SENSOR_PARAMS for s in _sensor_names(param)]

# Hidden fault-isolation nodes: when Unknown Anomaly fires, these represent evidence pointing to which subsystem the unexplained symptom signature is consistent with.
# ppO2/ppCO2 appear in both families — an unknown signature touching those sensors is genuinely ambiguous between subsystems, and both can activate together.
FAULT_ISOLATION_HIDDEN_NODES = {
    "[HIDDEN] Atmosphere Revitalization Fault Isolation": (
        _sensor_names("ppO2") + _sensor_names("ppCO2") + _sensor_names("Humidity")
    ),
    "[HIDDEN] Atmosphere Control and Supply Fault Isolation": (
        _sensor_names("ppCO2") + _sensor_names("ppO2") + _sensor_names("Total_Cabin_Pressure")
    ),
}

ANOMALY_SUBSYSTEMS = {
    "Atmosphere Revitalization": [
        "VCCR Particulate Filter Saturation",
        "O2 Delivery System Malfunction (IHab)",
        "O2 Delivery System Malfunction (HALO)",
        "VCCR Sorbent Bed Saturation",
        "OGA Failure",
    ],
    "Atmosphere Control and Supply": [
        "Module Decompression (IHab)",
        "Module Decompression (HALO)",
    ]
}

# # NOTE: NEW ON 09/16/2026
# # Hidden fault-isolation nodes: when Unknown Anomaly fires, these represent evidence pointing to which subsystem the unexplained symptom signature is consistent with.
# # ppO2/ppCO2 appear in both families — an unknown signature touching those sensors is genuinely ambiguous between subsystems, and both can activate together.
# FAULT_ISOLATION_HIDDEN_NODES = {
#     "[HIDDEN] Atmosphere Revitalization Fault Isolation": ["high ppCO2_IHab (IHab)", "high ppCO2_HALO (HALO)",
#                                                            "low ppCO2_IHab (IHab)", "low ppCO2_HALO (HALO)",
#                                                            "high ppO2_IHab (IHab)", "high ppO2_HALO (HALO)",
#                                                            "low ppO2_IHab (IHab)", "low ppO2_HALO (HALO)",
#                                                            "high Humidity_IHab (IHab)", "high Humidity_HALO (HALO)",
#                                                            "low Humidity_IHab (IHab)", "low Humidity_HALO (HALO)"],
#     "[HIDDEN] Atmosphere Control and Supply Fault Isolation": ["high ppCO2_IHab (IHab)", "high ppCO2_HALO (HALO)",
#                                                                "low ppCO2_IHab (IHab)", "low ppCO2_HALO (HALO)",
#                                                                "high ppO2_IHab (IHab)", "high ppO2_HALO (HALO)",
#                                                                "low ppO2_IHab (IHab)", "low ppO2_HALO (HALO)",
#                                                                "high Total_Cabin_Pressure_IHab (IHab)", "high Total_Cabin_Pressure_HALO (HALO)",
#                                                                "low Total_Cabin_Pressure_IHab (IHab)", "low Total_Cabin_Pressure_HALO (HALO)"]
# }

# Anomaly symptom definitions: which sensors must be off-nominal and at what threshold.
# Threshold values: 1 = warning (caution) or above, 2 = critical only.
# "sensors" is a list of (sensor_column_name, min_threshold) tuples.
# ALL listed sensors must meet their threshold for the anomaly to be considered present.
# NOTE: TRY TO FIGURE OUT HOW SENSORS CAN BE DIFFERENT FOR THE SAME ANOMALY
ANOMALY_SYMPTOMS = {
    "VCCR Particulate Filter Saturation": {
        "component": "[HIDDEN] VCCR Particulate Filter",
        "sensors": [
            ("low ppO2_IHab (IHab)", 1), ("low ppO2_HALO (HALO)", 1),
            ("high ppCO2_IHab (IHab)", 2), ("high ppCO2_HALO (HALO)", 2),
            ("high Humidity_IHab (IHab)", 1), ("high Humidity_HALO (HALO)", 1),
        ],
    },
    "VCCR Sorbent Bed Saturation": {
        "component": "[HIDDEN] VCCR Sorbent Bed",
        "sensors": [
            ("high ppCO2_IHab (IHab)", 2),
            ("high ppCO2_HALO (HALO)", 2),
        ],
    },
    "OGA Failure": {
        "component": "[HIDDEN] OGA Status Panel Indicator",
        "sensors": [
            ("low ppO2_IHab (IHab)", 1),
            ("high ppCO2_IHab (IHab)", 1),
            ("low ppO2_HALO (HALO)", 1),
            ("high ppCO2_HALO (HALO)", 1),
        ],
    },
    "O2 Delivery System Malfunction (IHab)": {
        "component": "[HIDDEN] Cabin O2 Valve Position Indicator (IHab)",
        "sensors": [
            ("low ppO2_IHab (IHab)", 1),
        ],
    },
    "O2 Delivery System Malfunction (HALO)": {
        "component": "[HIDDEN] Cabin O2 Valve Position Indicator (HALO)",
        "sensors": [
            ("low ppO2_HALO (HALO)", 1),
        ],
    },
    "Module Decompression (IHab)": {
        "component": "[HIDDEN] Module Pressure Leak (IHab)",
        "sensors": [
            ("low ppO2_IHab (IHab)", 1),
            ("low ppCO2_IHab (IHab)", 1),
            ("low Total_Cabin_Pressure_IHab (IHab)", 1),
        ],
    },
    "Module Decompression (HALO)": {
        "component": "[HIDDEN] Module Pressure Leak (HALO)",
        "sensors": [
            ("low ppO2_HALO (HALO)", 1),
            ("low ppCO2_HALO (HALO)", 1),
            ("low Total_Cabin_Pressure_HALO (HALO)", 1),
        ],
    },
}

# All anomaly names used in the Bayesian network
anomalies = ["OGA Failure", "VCCR Particulate Filter Saturation", "VCCR Sorbent Bed Saturation",
             "O2 Delivery System Malfunction (IHab)","O2 Delivery System Malfunction (HALO)",
             "Module Decompression (IHab)", "Module Decompression (HALO)",
             "Unknown Anomaly", "Atmosphere Revitalization", "Atmosphere Control and Supply"]

# for sig, info in ANOMALY_SYMPTOMS.items():
#     output = info.get("output", sig)
#     assert output in anomalies, f"'{sig}' maps to output '{output}', which isn't in the anomalies list"

NOMINAL_DATA_TICKS = 1000

# Nominal sensor values 
NOMINAL_SENSOR_TEMPLATE = {
    # ppO2 IHab
    'high ppO2_IHab (IHab)': 0, 'low ppO2_IHab (IHab)': 0,
    'high ppO2_IHab (IHab) (t-1)': 0, 'low ppO2_IHab (IHab) (t-1)': 0,
    'ppO2_IHab (IHab)_value': 20.762852,
    'ppO2_IHab (IHab)_monitoringResult': 'NOMINAL',
    'ppO2_IHab (IHab)_range': "{'min': 0.0, 'max': 3.4028235e+38}",
    'ppO2_IHab (IHab)_alarmThresholds': "{'WARNING_LOW': {'max': 20.665, 'min': 19.0}, 'WARNING_HIGH': {'max': 24.6646, 'min': 23.3314}, 'CRITICAL_LOW': {'max': 19.0, 'min': 0.0}, 'CRITICAL_HIGH': {'max': 4000.0, 'min': 24.6646}}",
    'ppO2_IHab (IHab)_input': 'IHab.O2',
    # ppO2 HALO
    'high ppO2_HALO (HALO)': 0, 'low ppO2_HALO (HALO)': 0,
    'high ppO2_HALO (HALO) (t-1)': 0, 'low ppO2_HALO (HALO) (t-1)': 0,
    'ppO2_HALO (HALO)_value': 20.750807,
    'ppO2_HALO (HALO)_monitoringResult': 'NOMINAL',
    'ppO2_HALO (HALO)_range': "{'min': 0.0, 'max': 3.4028235e+38}",
    'ppO2_HALO (HALO)_alarmThresholds': "{'WARNING_LOW': {'max': 20.665, 'min': 19.0}, 'WARNING_HIGH': {'max': 24.6646, 'min': 23.3314}, 'CRITICAL_LOW': {'max': 19.0, 'min': 0.0}, 'CRITICAL_HIGH': {'max': 4000.0, 'min': 24.6646}}",
    'ppO2_HALO (HALO)_input': 'HALO.O2',
    # Humidity HALO
    'high Humidity_HALO (HALO)': 0, 'low Humidity_HALO (HALO)': 0,
    'high Humidity_HALO (HALO) (t-1)': 0, 'low Humidity_HALO (HALO) (t-1)': 0,
    'Humidity_HALO (HALO)_value': 0.51796305,
    'Humidity_HALO (HALO)_monitoringResult': 'NOMINAL',
    'Humidity_HALO (HALO)_range': "{'min': 0.0, 'max': 1.0}",
    'Humidity_HALO (HALO)_alarmThresholds': "{'WARNING_LOW': {'max': 0.5, 'min': 0.4}, 'WARNING_HIGH': {'max': 0.7, 'min': 0.61}, 'CRITICAL_LOW': {'max': 0.4, 'min': 0.0}, 'CRITICAL_HIGH': {'max': 1.0, 'min': 0.7}}",
    'Humidity_HALO (HALO)_input': 'HALO.Vapor',
    # ppCO2 IHab
    'high ppCO2_IHab (IHab)': 0, 'low ppCO2_IHab (IHab)': 0,
    'high ppCO2_IHab (IHab) (t-1)': 0, 'low ppCO2_IHab (IHab) (t-1)': 0,
    'ppCO2_IHab (IHab)_value': 0.04107719,
    'ppCO2_IHab (IHab)_monitoringResult': 'NOMINAL',
    'ppCO2_IHab (IHab)_range': "{'min': 0.0, 'max': 3.4028235e+38}",
    'ppCO2_IHab (IHab)_alarmThresholds': "{'WARNING_LOW': {'max': 0.0, 'min': 0.026}, 'WARNING_HIGH': {'max': 0.164, 'min': 0.15}, 'CRITICAL_LOW': {'max': 0.0, 'min': 0.0}, 'CRITICAL_HIGH': {'max': 100.0, 'min': 0.164}}",
    'ppCO2_IHab (IHab)_input': 'IHab.CO2',
    # Humidity IHab
    'high Humidity_IHab (IHab)': 0, 'low Humidity_IHab (IHab)': 0,
    'high Humidity_IHab (IHab) (t-1)': 0, 'low Humidity_IHab (IHab) (t-1)': 0,
    'Humidity_IHab (IHab)_value': 0.51272607,
    'Humidity_IHab (IHab)_monitoringResult': 'NOMINAL',
    'Humidity_IHab (IHab)_range': "{'min': 0.0, 'max': 1.0}",
    'Humidity_IHab (IHab)_alarmThresholds': "{'WARNING_LOW': {'max': 0.5, 'min': 0.4}, 'WARNING_HIGH': {'max': 0.7, 'min': 0.61}, 'CRITICAL_LOW': {'max': 0.4, 'min': 0.0}, 'CRITICAL_HIGH': {'max': 1.0, 'min': 0.7}}",
    'Humidity_IHab (IHab)_input': 'IHab.Vapor',
    # ppCO2 HALO
    'high ppCO2_HALO (HALO)': 0, 'low ppCO2_HALO (HALO)': 0,
    'high ppCO2_HALO (HALO) (t-1)': 0, 'low ppCO2_HALO (HALO) (t-1)': 0,
    'ppCO2_HALO (HALO)_value': 0.043024577,
    'ppCO2_HALO (HALO)_monitoringResult': 'NOMINAL',
    'ppCO2_HALO (HALO)_range': "{'min': 0.0, 'max': 3.4028235e+38}",
    'ppCO2_HALO (HALO)_alarmThresholds': "{'WARNING_LOW': {'max': 0.0, 'min': 0.026}, 'WARNING_HIGH': {'max': 0.164, 'min': 0.15}, 'CRITICAL_LOW': {'max': 0.0, 'min': 0.0}, 'CRITICAL_HIGH': {'max': 100.0, 'min': 0.164}}",
    'ppCO2_HALO (HALO)_input': 'HALO.CO2',
    # Total Cabin Pressure IHab
    'high Total_Cabin_Pressure_IHab (IHab)': 0, 'low Total_Cabin_Pressure_IHab (IHab)': 0,
    'high Total_Cabin_Pressure_IHab (IHab) (t-1)': 0, 'low Total_Cabin_Pressure_IHab (IHab) (t-1)': 0,
    'Total_Cabin_Pressure_IHab (IHab)_value': 102.53237,
    'Total_Cabin_Pressure_IHab (IHab)_monitoringResult': 'NOMINAL',
    'Total_Cabin_Pressure_IHab (IHab)_range': "{'min': 0.0, 'max': 3.4028235e+38}",
    'Total_Cabin_Pressure_IHab (IHab)_alarmThresholds': "{'WARNING_LOW': {'max': 100.31872, 'min': 87.56342}, 'WARNING_HIGH': {'max': 104.8003, 'min': 102.7319}, 'CRITICAL_LOW': {'max': 87.56342, 'min': 0.0}, 'CRITICAL_HIGH': {'max': 110.0, 'min': 104.8003}}",
    'Total_Cabin_Pressure_IHab (IHab)_input': 'IHab',
    # Total Cabin Pressure HALO
    'high Total_Cabin_Pressure_HALO (HALO)': 0, 'low Total_Cabin_Pressure_HALO (HALO)': 0,
    'high Total_Cabin_Pressure_HALO (HALO) (t-1)': 0, 'low Total_Cabin_Pressure_HALO (HALO) (t-1)': 0,
    'Total_Cabin_Pressure_HALO (HALO)_value': 102.50009,
    'Total_Cabin_Pressure_HALO (HALO)_monitoringResult': 'NOMINAL',
    'Total_Cabin_Pressure_HALO (HALO)_range': "{'min': 0.0, 'max': 3.4028235e+38}",
    'Total_Cabin_Pressure_HALO (HALO)_alarmThresholds': "{'WARNING_LOW': {'max': 100.31872, 'min': 87.56342}, 'WARNING_HIGH': {'max': 104.8003, 'min': 102.7319}, 'CRITICAL_LOW': {'max': 87.56342, 'min': 0.0}, 'CRITICAL_HIGH': {'max': 110.0, 'min': 104.8003}}",
    'Total_Cabin_Pressure_HALO (HALO)_input': 'HALO',
    # Anomalies and groups — all nominal
    'OGA Failure': 0, 'VCCR Particulate Filter Saturation': 0, 'VCCR Sorbent Bed Saturation': 0,
    'O2 Delivery System Malfunction (IHab)': 0, 'O2 Delivery System Malfunction (HALO)': 0,
    'Module Decompression (IHab)': 0, 'Module Decompression (HALO)': 0,
    'Unknown Anomaly': 0, 'Atmosphere Revitalization': 0, 'Atmosphere Control and Supply': 0,
    # Hidden components — all inactive
    '[HIDDEN] VCCR Particulate Filter': 0,
    '[HIDDEN] OGA Status Panel Indicator': 0,
    '[HIDDEN] Cabin O2 Valve Position Indicator (IHab)': 0,
    '[HIDDEN] Cabin O2 Valve Position Indicator (HALO)': 0,
    '[HIDDEN] VCCR Sorbent Bed': 0,
    '[HIDDEN] Module Pressure Leak (IHab)': 0,
    '[HIDDEN] Module Pressure Leak (HALO)': 0,
    # Fault isolation hidden components — all inactive <-- NOTE: NEW CODE ADDED ON 09/16/2026
    '[HIDDEN] Atmosphere Revitalization Fault Isolation': 0,
    '[HIDDEN] Atmosphere Control and Supply Fault Isolation': 0
}


def generate_nominal_rows(n, fan_status=None):
    # Generate n rows of nominal data
    base_row = dict(NOMINAL_SENSOR_TEMPLATE)
    if fan_status is None or fan_status == 'open':
        base_row['Fan Status'] = 1
    elif fan_status == 'closed':
        base_row['Fan Status'] = 0
    final_rows = []
    for i in range(n):
        row = base_row.copy()
        row['tick'] = i
        final_rows.append(row)
    return final_rows


def resolve_anomalies_for_tick(sensor_row, fan_status, anomalies_list):
    """
    Determine which anomalies are active for a single tick.

    Strategy:
    - Collect active sensors per module (IHab, HALO)
    - For CDRA and BFS: check cross-module (fan on) or per-module (fan off)
    - For all others: always module-specific
    - Only flag the most complex anomaly that fully covers active sensors,
      suppressing simpler ones whose sensors are a strict subset.
    - When fan is off, suppression is evaluated per-module independently.

    Returns a dict of {anomaly_name: 0 or 1} for all anomalies in anomalies_list.
    """

    # NOTE: Updated on 08/26/26 to capture both types of VCCR failure signatures
    CROSS_MODULE_ANOMALIES = {"VCCR Particulate Filter Saturation", "VCCR Sorbent Bed Saturation", "OGA Failure"}

    # NOTE: NEW CODE ON 09/16/2026
    # --- 1. Collect all off-nominal sensors across the full model, not just
    # sensors that appear in some known anomaly's symptom list. This is what
    # lets Unknown Anomaly fire on a genuinely novel signature, since a sensor
    # can be off-nominal (1=warning or 2=critical) without belonging to any
    # ANOMALY_SYMPTOMS entry.
    all_active = {s: sensor_row.get(s, 0) for s in ALL_SENSOR_NAMES if sensor_row.get(s, 0) >= 1}

    # # --- 1. Collect all active sensors ---
    # all_active = {}
    # for anom_info in ANOMALY_SYMPTOMS.values():
    #     for sensor, threshold in anom_info["sensors"]:
    #         val = sensor_row.get(sensor, 0)
    #         if val >= threshold:
    #             all_active[sensor] = val

    # --- 2. Helper: get required sensors for an anomaly, optionally filtered by module ---
    def required_sensors(anom_name, module=None):
        """
        Return the set of required sensor names for anom_name.
        If module is 'IHab' or 'HALO', restrict to sensors for that module only.
        """
        sensors = ANOMALY_SYMPTOMS[anom_name]["sensors"]
        if module is not None:
            return {s for s, _ in sensors if s.endswith(f"({module})")}
        return {s for s, _ in sensors}

    def all_symptoms_present(anom_name, module=None):
        """
        Return True if all required sensors for anom_name are active.
        If module is specified, only check sensors for that module.
        A required sensor not belonging to the specified module is ignored
        (treated as satisfied), allowing per-module partial checks.
        """
        for sensor, threshold in ANOMALY_SYMPTOMS[anom_name]["sensors"]:
            if module is not None and not sensor.endswith(f"({module})"):
                continue
            if sensor_row.get(sensor, 0) < threshold:
                return False
        return True

    # --- 3a. Cross-module anomalies (CDRA, BFS) ---
    # Fan ON:  all sensors in both modules must be active simultaneously
    # Fan OFF: symptoms in EITHER module alone are sufficient to flag
    flagged = set()

    for anom_name in CROSS_MODULE_ANOMALIES:
        if anom_name not in ANOMALY_SYMPTOMS:
            continue

        if fan_status == 'off':
            if all_symptoms_present(anom_name, module='IHab') or \
               all_symptoms_present(anom_name, module='HALO'):
                flagged.add(anom_name)
        else:
            if all_symptoms_present(anom_name):
                flagged.add(anom_name)

    # --- 3b. Module-specific anomalies ---
    for anom_name in ANOMALY_SYMPTOMS:
        if anom_name in CROSS_MODULE_ANOMALIES:
            continue
        if all_symptoms_present(anom_name):
            flagged.add(anom_name)

    # --- 4. Suppress simpler anomalies ---
    # An anomaly A is suppressed by anomaly B if:
    #   - B is also flagged
    #   - required_sensors(A) is a strict subset of required_sensors(B)
    #   - When fan is OFF, this subset check is done per-module independently:
    #       A is suppressed only if its per-module sensor set is a strict subset
    #       of B's per-module sensor set for the SAME module.
    #     This prevents cross-module suppression when atmospheres are isolated.
    #   - When fan is ON, the full sensor sets are compared (original behavior).
    #
    # Example (fan off, IHab only active):
    #   Emergency O2 (IHab) requires {low ppO2_IHab}
    #   BFS requires {low ppO2_IHab, high ppCO2_IHab} for IHab module
    #   Since {low ppO2_IHab} ⊂ {low ppO2_IHab, high ppCO2_IHab}, Emergency O2 is suppressed.
    #
    # Example (fan off, only IHab active, CDRA fired from IHab sensors):
    #   Emergency O2 (IHab) IHab-sensors = {low ppO2_IHab}
    #   CDRA IHab-sensors = {low ppO2_IHab, high ppCO2_IHab, high Humidity_IHab}
    #   {low ppO2_IHab} ⊂ CDRA's IHab sensors → Emergency O2 (IHab) suppressed. ✓
    #
    # Example (fan off, HALO humidity absent, BFS fired from IHab):
    #   Excess CO2 (HALO) HALO-sensors = {high ppCO2_HALO}
    #   BFS HALO-sensors = {low ppO2_HALO, high ppCO2_HALO}
    #   BFS didn't fire from HALO (ppO2_HALO absent), so no suppression of Excess CO2 (HALO). ✓

    to_suppress = set()
    flagged_list = list(flagged)

    for anom_a in flagged_list:
        for anom_b in flagged_list:
            if anom_a == anom_b:
                continue

            if fan_status == 'off':
                # Check suppression independently per module.
                # A is suppressed by B if, for every module where A has required sensors,
                # A's sensors in that module are a strict subset of B's sensors in that module,
                # AND B actually fired based on that module's sensors.
                suppressed_by_b = False
                for module in ('IHab', 'HALO'):
                    req_a_mod = required_sensors(anom_a, module=module)
                    req_b_mod = required_sensors(anom_b, module=module)

                    if not req_a_mod:
                        # A has no sensors in this module, skip
                        continue

                    # B must have fired from this module's sensors specifically
                    b_fires_from_module = all_symptoms_present(anom_b, module=module)

                    if req_a_mod < req_b_mod and b_fires_from_module:
                        suppressed_by_b = True
                        break

                if suppressed_by_b:
                    to_suppress.add(anom_a)
                    break

            else:
                # Fan ON: full sensor set comparison
                if required_sensors(anom_a) < required_sensors(anom_b):
                    to_suppress.add(anom_a)
                    break

    final_anomalies = flagged - to_suppress

    # --- 5. Build result dict, set group columns and Unknown Anomaly ---
    result = {a: 0 for a in anomalies_list}
    for anom_name in final_anomalies:
        if anom_name in result:
            result[anom_name] = 1

    for subsystem_name, subsystem_anomalies in ANOMALY_SUBSYSTEMS.items():
        result[subsystem_name] = int(any(result.get(a, 0) == 1 for a in subsystem_anomalies))

    # Unknown Anomaly: sensors are active but none are explained by any flagged known anomaly
    explained_sensors = set()
    for anom_name in final_anomalies:
        explained_sensors |= required_sensors(anom_name)

    known_anomaly_nodes = {a for a in anomalies_list
                            if a not in ("Unknown Anomaly", "Atmosphere Revitalization", "Atmosphere Control and Supply")}
    no_known_anomalies = not any(result.get(a, 0) == 1 for a in known_anomaly_nodes)
    unexplained_active = set(all_active.keys()) - explained_sensors
    result["Unknown Anomaly"] = int(no_known_anomalies and bool(unexplained_active))

    # NOTE: NEW CODE ON 09/16/2026
    # Hidden fault-isolation evidence: only activates alongside Unknown Anomaly, driven by which unexplained sensors are active.
    for node_name, sensor_names in FAULT_ISOLATION_HIDDEN_NODES.items():
        active_for_node = any(sensor_row.get(s, 0) >= 1 for s in sensor_names)
        result[node_name] = int(result["Unknown Anomaly"] == 1 and active_for_node)

    return result


def parse_simulation_ticks(data, anomaly_name, anomaly_tick, anomalies_list,
                          halo_anomaly=None, halo_sensors=None, second_anomaly=None, fan_status=None):
    """
    Parse tick snapshots from a single simulation run into row dicts.
    
    Args:
        data: JSON response from the simulation log endpoint
        anomaly_name: The anomaly to inject for this config (or None for baseline)
        anomaly_tick: The tick number at which the anomaly activates (or None)
        anomalies_list: Full list of anomaly names used in the Bayesian network
        halo_anomaly: Optional habitat-wide anomaly name to inject when
                      specified HALO sensors show off-nominal values
        halo_sensors: List of HALO sensor name substrings to check for symptoms
                      (e.g. ['ppCO2_HALO', 'Humidity_HALO'] for CDRA,
                       ['ppO2_HALO'] for bio filter)
    
    Returns:
        List of row dicts suitable for DataFrame construction
    """
    
    history = defaultdict(lambda: deque(maxlen=30))
    rows = []
    crew_death_tick = None # set once all crew are confirmed dead

    for idx, tick in enumerate(data.get('ticks', [])):
        tick_num = tick.get('tick', idx)
        modules_state = tick.get('modules', {})


        # --- Crew death detection ---
        # Find any CrewGroup module in this tick's snapshot and check O2Consumed.
        # kill() in CrewPerson.java sets O2Consumed = 0f; alive crew always > 0.
        if crew_death_tick is None:
            for mod_name, mod in modules_state.items():
                if mod.get('moduleType') == 'CrewGroup':
                    people = mod.get('properties', {}).get('crewPeople', [])
                    if people and all(p.get('O2Consumed', 1.0) == 0.0 for p in people):
                        crew_death_tick = tick_num
                        print(f"    ⚠️  Crew death detected in log at tick {tick_num} "
                              f"— truncating training data here")
                        break
 
        # Stop appending rows from the death tick onward
        if crew_death_tick is not None and tick_num >= crew_death_tick:
            break       
       
       
        sensor_row = {'tick': tick_num + NOMINAL_DATA_TICKS}

        param_names = []
        for mod_name, mod in modules_state.items():
            module_type = mod.get('moduleType', '')
            if "Sensor" in module_type:
                props = mod.get('properties', {})
                input_val = mod.get('input')
                if input_val is None:
                    if "_" in mod_name:
                        input_val = mod_name.split("_")[-1]
                    else:
                        input_val = ""
                base_name = f"{mod_name} ({input_val})"
                
                # Create two columns for split parameters
                high_param_name = f'high {base_name}'
                low_param_name = f'low {base_name}'
                # Create two columns for high/low (t-1) parameters
                prev_high_param_name = f'high {base_name} (t-1)'
                prev_low_param_name = f'low {base_name} (t-1)'

                param_names.extend([high_param_name, low_param_name, prev_high_param_name, prev_low_param_name])

                if 'value' in props:
                    # Get the monitoring result
                    if "monitoringResult" in props:
                        result = props["monitoringResult"]
                        # Map levels for high and low parameters
                        sensor_row[high_param_name] = (
                            2 if 'CRITICAL_HIGH' in result else
                            1 if 'WARNING_HIGH' in result else 0
                        )
                        sensor_row[low_param_name] = (
                            2 if 'CRITICAL_LOW' in result else
                            1 if 'WARNING_LOW' in result else 0
                        )

                        # Get t-30 (t-1) result
                        history_queue = history[base_name]
                        if len(history_queue) >= 30: # if length is 30, t-30 exists
                            t_minus_30_result = history_queue[0]
                            sensor_row[prev_high_param_name] = (
                                2 if 'CRITICAL_HIGH' in t_minus_30_result else
                                1 if 'WARNING_HIGH' in t_minus_30_result else 0
                            )
                            sensor_row[prev_low_param_name] = (
                                2 if 'CRITICAL_LOW' in t_minus_30_result else
                                1 if 'WARNING_LOW' in t_minus_30_result else 0
                            )
                        else:
                            sensor_row[prev_high_param_name] = 0
                            sensor_row[prev_low_param_name] = 0
                        # Append current result to history
                        history_queue.append(result)

                # Store all properties
                for prop_key, prop_val in props.items():
                    column_name = f"{base_name}_{prop_key}"
                    sensor_row[column_name] = prop_val

        # Define the fan status for the current simulation
        if fan_status is None or fan_status == 'on':
            sensor_row['Fan Status'] = 1
        elif fan_status == 'off':
            sensor_row['Fan Status'] = 0

        # Symptom-based anomaly injection
        # 1. Set hidden component = 1 at the malfunction tick, explicitly adding zeros to all other hidden component nodes
        active_components = set()
        if anomaly_name is not None and anomaly_tick is not None and tick_num is not None:
            if anomaly_name in ANOMALY_SYMPTOMS:
                comp = ANOMALY_SYMPTOMS[anomaly_name]["component"]
                sensor_row[comp] = int(tick_num >= anomaly_tick)
                active_components.add(ANOMALY_SYMPTOMS[anomaly_name]["component"])
            # For second_anomaly (e.g., default_leak sets both IHab and HALO)
            if second_anomaly is not None and second_anomaly in ANOMALY_SYMPTOMS:
                comp2 = ANOMALY_SYMPTOMS[second_anomaly]["component"]
                sensor_row[comp2] = int(tick_num >= anomaly_tick)
                active_components.add(ANOMALY_SYMPTOMS[second_anomaly]["component"])

        for anom_info in ANOMALY_SYMPTOMS.values():
            comp = anom_info["component"]
            if comp not in active_components:
                sensor_row[comp] = 0 # set non-faulty components to zero

        # 2. Identify anomalies based on symptoms and also if there is high ppco2 in ihab it triggers excess co2 ihab and similar for halo and emergency o2
        # And if ppo2 is low in ihab and halo and if ppco2 is high only in ihab, it would trigger bfs and also emergency o2 in halo but if ppco2 is also high in halo, then it only triggers bfs. similar for cdra
        resolved = resolve_anomalies_for_tick(sensor_row, fan_status, anomalies_list)
        sensor_row.update(resolved)

        # met_anomalies = []
        # for anom_name, anom_info in ANOMALY_SYMPTOMS.items():
        #     ihab_sensors = [i for i in anom_info["sensors"] if i[0].endswith("(IHab)")]
        #     halo_sensors = [i for i in anom_info["sensors"] if i[0].endswith("(HALO)")]

        #     if fan_status == 'off':
        #         subsets_to_check = [ihab_sensors]
        #     else:
        #         subsets_to_check = [anom_info["sensors"], ihab_sensors, halo_sensors]

        #     best_met_sensors = None
        #     for sensors_subset in subsets_to_check:
        #         if not sensors_subset:
        #             continue

        #         all_symptoms_met = all(
        #             sensor_row.get(sensor, 0) >= threshold
        #             for sensor, threshold in sensors_subset
        #         )
                
        #         if all_symptoms_met:
        #             # Keep the largest subset of symptoms that is met
        #             if best_met_sensors is None or len(sensors_subset) > len(best_met_sensors):
        #                 best_met_sensors = set(sensor for sensor, threshold in sensors_subset)
            
        #     if best_met_sensors:
        #         met_anomalies.append({
        #             'name': anom_name,
        #             'sensors': best_met_sensors
        #         })

        # # Ensure all anomaly columns exist with default 0
        # for anomaly in anomalies_list:
        #     sensor_row.setdefault(anomaly, 0)

        # # Filter out anomalies whose symptoms are a subset of another met anomaly
        # final_anomalies = []
        # for anom in met_anomalies:
        #     is_subset = False
        #     for other_anom in met_anomalies:
        #         if anom['name'] != other_anom['name']:
        #             # If this anomaly's sensors are a strict subset of another anomaly's sensors
        #             if anom['sensors'].issubset(other_anom['sensors']):
        #                 is_subset = True
        #                 break
        #     if not is_subset:
        #         final_anomalies.append(anom['name'])

        # for anom_name in final_anomalies:
        #     sensor_row[anom_name] = 1

        # # Ensure all anomaly columns exist with default 0
        # for anomaly in anomalies_list:
        #     sensor_row.setdefault(anomaly, 0)

        # # Set group columns based on active anomalies
        # for subsystem_name, subsystem_anomalies in ANOMALY_SUBSYSTEMS.items():
        #     sensor_row[subsystem_name] = int(any(
        #         sensor_row.get(a, 0) == 1 for a in subsystem_anomalies
        #     ))

        # # Check whether any known anomalies are present
        # no_known_anomalies = all(sensor_row[anomaly] != 1 for anomaly in anomalies_list)
        # # Check whether any parameter values are off-nominal
        # no_active_params = all(sensor_row.get(param, 0) == 0 for param in param_names)

        # if no_known_anomalies and not no_active_params:
        #     sensor_row['Unknown Anomaly'] = 1
        # else:
        #     sensor_row['Unknown Anomaly'] = 0

        # Only store if sensor values are found
        if len(sensor_row) > 1: # more than just tick
            rows.append(sensor_row)

    return rows


def run_simulation(server_url, config_path, num_ticks):
    """
    Start a simulation with the given config, advance it, and return the log data.
    
    Args:
        server_url: BioSim server URL
        config_path: Path to the .biosim config file
        num_ticks: Number of ticks to advance the simulation
    
    Returns:
        JSON log data from the simulation
    """
    # Read the config file
    with open(config_path, 'r') as f:
        biosim_xml = f.read()

    # Lock for the start call
    with _start_lock:
        # Submit the XML config and get a simulation ID
        resp = requests.post(
            f'{server_url}/api/simulation/start',
            headers={'Content-Type': 'text/plain'},
            data=biosim_xml
        )
        if not resp.ok:
            raise RuntimeError(f"Failed to start simulation for {config_path}: {resp.status_code} {resp.text}")
        simID = resp.json()['simId']
        print(f"    Started {os.path.basename(config_path)} → simID={simID}")


    # Determine which CrewGroup module name to watch by parsing the config XML.
    # Looks for <CrewGroup moduleName="..."> — falls back to None (no early stop).
    import xml.etree.ElementTree as ET
    crew_module_name = None
    try:
        ns = {'b': 'http://www.traclabs.com/biosim'}
        root = ET.fromstring(biosim_xml)
        cg = root.find('.//b:CrewGroup', ns)
        if cg is not None:
            crew_module_name = cg.get('moduleName')
    except Exception:
        pass  # non-fatal — early-stop just won't trigger


    # Tick advancement runs outside the lock
    for i in range(num_ticks):
        resp = requests.post(f'{server_url}/api/simulation/{simID}/tick')
        time.sleep(0.02) # small delay to avoid overwhelming the server

        # Poll crew status every 10 ticks to detect death without hammering the server.
        # O2Consumed == 0.0 for every crew member is the reliable death signal
        # (kill() sets it to 0f explicitly in CrewPerson.java).
        if crew_module_name and i % 10 == 0:
            try:
                mod_resp = requests.get(
                    f'{server_url}/api/simulation/{simID}/modules/{crew_module_name}',
                    timeout=2
                )
                if mod_resp.ok:
                    crew_data = mod_resp.json()
                    people = crew_data.get('properties', {}).get('crewPeople', [])
                    if people and all(p.get('O2Consumed', 1.0) == 0.0 for p in people):
                        print(f"    ⚠️  All crew dead at tick {i} — stopping early "
                              f"({num_ticks - i} ticks remaining)")
                        break
            except Exception:
                pass  # non-fatal — continue ticking if poll fails        


    resp = requests.get(f'{server_url}/api/simulation/{simID}/log')
    if not resp.ok:
        raise RuntimeError(f"Failed to get simulation log for {config_path}: {resp.status_code} {resp.text}")

    data = resp.json()
    return data


def run_single_config(config_name, config_info, server_url, num_ticks):
    """
    Run a single simulation config end-to-end: simulate + parse.
    Returns (config_name, rows, elapsed_seconds).
    Thread-safe — no shared mutable state.
    """
    t0 = time.time()
    config_path = os.path.join(CONFIG_DIR, config_name)
    anomaly_name = config_info['anomaly']
    anomaly_tick = config_info['tick']
    fan_status = config_info.get('fan_status', None)
    halo_anomaly = config_info.get('halo_anomaly', None)
    halo_sensors = config_info.get('halo_sensors', None)
    second_anomaly = config_info.get('second_anomaly', None)

    data = run_simulation(server_url, config_path, num_ticks)
    rows = parse_simulation_ticks(data, anomaly_name, anomaly_tick, anomalies,
                                 halo_anomaly=halo_anomaly, halo_sensors=halo_sensors,
                                 second_anomaly=second_anomaly, fan_status=fan_status)
    
    # Prepend hardcoded nominal data before the anomaly rows
    nominal_rows = generate_nominal_rows(NOMINAL_DATA_TICKS, fan_status=fan_status)
    all_config_rows = nominal_rows + rows
    elapsed = time.time() - t0
    return config_name, all_config_rows, elapsed


def get_ordered_bn_columns(all_nodes):
    sensors = ['ppCO2', 'ppO2', 'Humidity', 'Total_Cabin_Pressure']
    locations = ['HALO', 'IHab']
    param_nodes_ordered = []
    for sensor in sensors:
        for loc in locations:
            low = next((n for n in all_nodes if f'low {sensor} ({loc})' in n and '(t-1)' not in n), None)
            high = next((n for n in all_nodes if f'high {sensor} ({loc})' in n and '(t-1)' not in n), None)
            if low: param_nodes_ordered.append(low)
            if high: param_nodes_ordered.append(high)
    anomaly_nodes_ordered = [n for n in anomalies if n in all_nodes]
    hidden_nodes_ordered = [n for n in all_nodes if '[HIDDEN]' in n]
    other_nodes_ordered = [
        n for n in all_nodes if n not in param_nodes_ordered
                                 and n not in anomaly_nodes_ordered
                                 and n not in hidden_nodes_ordered
    ]
    return param_nodes_ordered + anomaly_nodes_ordered + hidden_nodes_ordered + other_nodes_ordered


# Run simulation with threads
def run_all_simulations_threaded(max_workers, num_ticks, server_url=SERVER_URL):
    """
    Run all configs in parallel using ThreadPoolExecutor.
    Returns (all_rows, total_elapsed, per_config_times).
    """
    all_rows = []
    per_config_times = {}

    t_total_start = time.time()

    with ThreadPoolExecutor(max_workers=max_workers) as executor:
        futures = {
            executor.submit(run_single_config, name, info, server_url, num_ticks): name
            for name, info in CONFIG_ANOMALY_MAP.items()
        }

        for future in as_completed(futures):
            config_name = futures[future]
            try:
                name, rows, elapsed = future.result()
                per_config_times[name] = elapsed
                all_rows.extend(rows)
                print(f"  [Thread] {name}: {len(rows)} rows in {elapsed:.2f}s")
            except Exception as e:
                per_config_times[config_name] = -1
                print(f"  [Thread] ERROR {config_name}: {e}")

    total_elapsed = time.time() - t_total_start
    return all_rows, total_elapsed, per_config_times


# Run simulation without threads
def run_all_simulations_sequential(num_ticks, server_url=SERVER_URL):
    """
    Run all configs sequentially (baseline for comparison).
    Returns (all_rows, total_elapsed, per_config_times).
    """
    all_rows = []
    per_config_times = {}

    t_total_start = time.time()

    for config_name, config_info in CONFIG_ANOMALY_MAP.items():
        try:
            name, rows, elapsed = run_single_config(config_name, config_info, server_url, num_ticks)
            per_config_times[name] = elapsed
            all_rows.extend(rows)
            print(f"  [Sequential] {name}: {len(rows)} rows in {elapsed:.2f}s")
        except Exception as e:
            per_config_times[config_name] = -1
            print(f"  [Sequential] ERROR {config_name}: {e}")

    total_elapsed = time.time() - t_total_start
    return all_rows, total_elapsed, per_config_times


# NOTE: NEW CODE ON 09/16/2026
# Add noise to labeled data
def add_anomaly_label_noise_df(df, noise_rate=0.01, seed=42):
    """
    Flip exactly noise_rate of all positive anomaly/Unknown Anomaly
    labels from 1 to 0.
    """

    rng = np.random.default_rng(seed)

    noisy_columns = [
        a for a in anomalies
        if a not in {
            "Atmosphere Revitalization",
            "Atmosphere Control and Supply"
        }
        and a in df.columns
    ]

    # Boolean mask of all positive anomaly labels
    positive_mask = df[noisy_columns].eq(1)

    # Get locations of all positive labels
    positive_locations = np.argwhere(positive_mask.to_numpy())

    total_positive = len(positive_locations)

    if total_positive == 0:
        print("No positive anomaly labels found; no noise added.")
        return df

    num_to_flip = int(round(total_positive * noise_rate))

    selected = rng.choice(
        total_positive,
        size=num_to_flip,
        replace=False
    )

    # Flip selected labels
    for idx in selected:
        row_idx, col_idx = positive_locations[idx]
        column = noisy_columns[col_idx]
        df.iat[row_idx, df.columns.get_loc(column)] = 0

    print(f"Added anomaly label noise: {num_to_flip}/{total_positive} ({100 * num_to_flip / total_positive:.2f}%) positive labels flipped 1 → 0")

    return df


# Function for parameter learning and saving the CPDs to a file
def run_parameter_learning(all_rows, output_prefix="threaded"):
    """Run Bayesian Estimator parameter learning on collected simulation data."""
    from pgmpy.estimators import BayesianEstimator as BE

    t0 = time.time()

    df_full = pd.DataFrame(all_rows)
    print(f"\nFull dataset shape: {df_full.shape}")

    # Add noise to 1% of anomaly labels
    df_full = add_anomaly_label_noise_df(df_full, noise_rate=0.01, seed=42)

    # Save DataFrame for parameter learning
    full_filepath = f'biosim_full_{output_prefix}.csv'
    df_full.to_csv(full_filepath, index=False)
    print(f'Saved full biosim dataset to {full_filepath}')

    # Extract relevant columns for parameter learning dataset
    ordered_cols = get_ordered_bn_columns(model.nodes())
    df_training = df_full[[col for col in ordered_cols if col in df_full.columns]]
    print(f'Training dataset shape: {df_training.shape}')

    training_filepath = f'biosim_training_dataset_{output_prefix}.csv'
    df_training.to_csv(training_filepath, index=False)
    print(f'Saved training dataset to {training_filepath}')

    # Create samples from biosim training dataset
    samples = df_training

    new_model = BayesianNetwork(ebunch = model.edges())

    state_names = {}
    for node in new_model.nodes():
        if '[HIDDEN]' in node or node in anomalies or node == 'Fan Status':
            state_names[node] = [0, 1]
        else:
            state_names[node] = [0, 1, 2]

    estimator = BE(new_model, samples, state_names=state_names)

    # If different prior strengths are desired for different anomalies in the network (for example,
    # having greater confidence in a CDRA failure prior than an Unknown Anomaly), a library of node
    # priors can be set up here
    PRIOR_STRENGTH = 5

    def compute_alpha(node, model, state_names):
        """
        Compute the per-node alpha so that the total prior pseudocounts = PRIOR_STRENGTH,
        regardless of the CPD dimensions
        """
        parents = model.get_parents(node)
        # Find the cardinality of the node in question
        k = len(state_names[node])

        if not parents:
            # Root node: CPD is just k states
            return PRIOR_STRENGTH / k
        else:
            # Compute the number of parent combinations for a given child node
            num_parent_combos = prod(len(state_names[p]) for p in parents)
            # Total CPD entries = k * num_parent_combos
           
            # if node == '[HIDDEN] BFS Component' or node == '[HIDDEN] CDRA Failure Component':
            #     # print(f'Alpha for {node}: {PRIOR_STRENGTH / (k * num_parent_combos)}')
            #     return PRIOR_STRENGTH / (2 * k * num_parent_combos)
            # else:
            return PRIOR_STRENGTH / (k * num_parent_combos)
        
    # Build the pseudo_counts dictionary expected by BayesianEstimator
    # Updated to have the correct shape for each specific node
    def build_node_pseudo_counts(node, model, state_names, alpha):
        """
        Build pseudo_counts in the shape pgmpy expects for a given node:
        (k, num_parent_combos) as a list of lists
        """
        parents = model.get_parents(node)
        k = len(state_names[node])

        if not parents:
            num_parent_combos = 1
        else:
            num_parent_combos = prod(len(state_names[p]) for p in parents)

        # Shape: (k, num_parent_combos) — each row is a state, each col is a parent combo
        return [[alpha] * num_parent_combos for _ in range(k)]        

    # Store learned nodes to determine which nodes need to be learned from data
    known_nodes = {cpd.variable for cpd in known_cpds}
    nodes_to_learn = [n for n in new_model.nodes if n not in known_nodes]

    learned_cpds = []
    for node in nodes_to_learn:        
        alpha = compute_alpha(node, new_model, state_names)
        # print(f'alpha: {alpha}')
        node_pseudo_counts = build_node_pseudo_counts(node, new_model, state_names, alpha)

        # Use .estimate_cpd method instead of .get_parameters as we are learning only a subset of the network's CPDs
        cpd = estimator.estimate_cpd(
            node,
            prior_type='dirichlet',
            pseudo_counts=node_pseudo_counts) # can update pseudo_counts dictionary if priors too uniform
        
        cpd.values = np.round(cpd.values, decimals=4)
        # Renormalize along axis 0 (each column of parent combinations sums to 1)
        # NOTE: Confirm that the follow normalization does not introduce any issues
        col_sums = cpd.values.sum(axis=0, keepdims=True)
        cpd.values = cpd.values / col_sums
        cpd.values = np.round(cpd.values, decimals=4)  # re-round after normalizing
    
        learned_cpds.append(cpd)

    for cpd in learned_cpds:
        print(cpd)

    cpds_filepath = os.path.join(current_dir, 'training_data', f'all_cpds_{output_prefix}.txt')

    with open(cpds_filepath, 'w') as f:
        f.write("=== Learned CPDs ===\n\n")
        for cpd in learned_cpds:
            # f.write(str(cpd))
            # f.write('\n\n')
            f.write(f"Variable: {cpd.variable}\n")
            f.write(f"Parents: {cpd.variables[1:]}\n")
            f.write(f"Values:\n{cpd.get_values()}\n\n")
        f.write("=== Known CPDs ===\n\n")
        for cpd in known_cpds:
            f.write(str(cpd))
            f.write('\n\n')
            # f.write(f"Variable: {cpd.variable}\n")
            # f.write(f"Parents: {cpd.variables[1:]}\n")
            # f.write(f"Values:\n{cpd.get_values()}\n\n")
    print(f'Saved CPDs to {cpds_filepath}')

    # Add learned CPDs to known deterministic CPDs previously defined
    new_model.add_cpds(*learned_cpds, *known_cpds)
    print('Model valid:', new_model.check_model())

    # Save the model
    model_filepath = os.path.join(current_dir, 'model', 'learned_model.pkl')
    with open(model_filepath, 'wb') as f:
        pickle.dump(new_model, f)
    print(f'Saved trained model to {model_filepath}')

    be_elapsed = time.time() - t0
    print(f'Parameter learning took {be_elapsed:.2f}s')
    return be_elapsed


def start_biosim_server():
    """Start the BioSim Java server and wait for it to be ready."""
    jar_path = os.path.join(_mars_repos_dir, 'biosim', 'target', 'biosim-2.0.0-jar-with-dependencies.jar')
    proc = subprocess.Popen(['java', '-jar', jar_path, '--writeTicks'])
    print('Starting BioSim server...')

    for attempt in range(30):
        try:
            resp = requests.get(f'{SERVER_URL}/api/simulation', timeout=2)
            if resp.ok:
                print(f'BioSim server ready after {attempt + 1}s')
                return proc
        except requests.ConnectionError:
            pass
        time.sleep(1)

    print('Warning: BioSim server may not be ready, proceeding anyway...')
    return proc


def stop_biosim_server(proc):
    """Terminate the BioSim server."""
    if proc:
        proc.terminate()
        proc.wait(timeout=10)
        print('BioSim server stopped.')


# Testing: run tests across different thread counts and tick counts
def run_testing(worker_counts, tick_counts):
    """
    Run simulations across all combinations of worker_counts and tick_counts.
    Collects timing data and prints a summary table.
    """
    results = []  # list of dicts: {workers, ticks, total_time, sim_time, be_time, rows}

    for num_ticks in tick_counts:
        for num_workers in worker_counts:
            label = f"sequential" if num_workers == 1 else f"{num_workers} threads"
            print(f"\n{'='*70}")
            print(f"  TESTING: {label}, {num_ticks} ticks")
            print(f"{'='*70}")

            server_proc = start_biosim_server()

            try:
                t_run_start = time.time()

                if num_workers == 1:
                    all_rows, sim_time, per_config = run_all_simulations_sequential(num_ticks)
                else:
                    all_rows, sim_time, per_config = run_all_simulations_threaded(num_workers, num_ticks)

                num_rows = len(all_rows)
                print(f"\n  Simulation phase: {sim_time:.2f}s, {num_rows} rows collected")

                # Run BE parameter learning
                if num_rows > 0:
                    be_time = run_parameter_learning(all_rows, output_prefix=f"w{num_workers}_t{num_ticks}")
                else:
                    be_time = 0.0
                    print("  Skipping BE learning (no data)")

                total_time = time.time() - t_run_start

                results.append({
                    'workers': num_workers,
                    'ticks': num_ticks,
                    'sim_time': sim_time,
                    'be_time': be_time,
                    'total_time': total_time,
                    'rows': num_rows,
                    'configs': len(CONFIG_ANOMALY_MAP),
                })

            except Exception as e:
                print(f"  TESTING ERROR: {e}")
                results.append({
                    'workers': num_workers,
                    'ticks': num_ticks,
                    'sim_time': -1,
                    'be_time': -1,
                    'total_time': -1,
                    'rows': 0,
                    'configs': len(CONFIG_ANOMALY_MAP),
                })
            finally:
                stop_biosim_server(server_proc)
                time.sleep(3) # give port time to free up

    # Print summary table
    print(f"\n\n{'='*90}")
    print(f"  TESTING RESULTS SUMMARY")
    print(f"{'='*90}")
    print(f"{'Workers':>8} | {'Ticks':>6} | {'Sim Time':>10} | {'BE Time':>10} | {'Total Time':>11} | {'Rows':>7} | {'Speedup':>8}")
    print(f"{'-'*8}-+-{'-'*6}-+-{'-'*10}-+-{'-'*10}-+-{'-'*11}-+-{'-'*7}-+-{'-'*8}")

    # Sequential times for speedup calculation
    baseline_times = {}
    for r in results:
        if r['workers'] == 1 and r['sim_time'] > 0:
            baseline_times[r['ticks']] = r['sim_time']

    for r in results:
        sim_str = f"{r['sim_time']:.2f}s" if r['sim_time'] >= 0 else "ERROR"
        be_str = f"{r['be_time']:.2f}s" if r['be_time'] >= 0 else "ERROR"
        total_str = f"{r['total_time']:.2f}s" if r['total_time'] >= 0 else "ERROR"

        baseline = baseline_times.get(r['ticks'], None)
        if baseline and r['sim_time'] > 0:
            speedup = f"{baseline / r['sim_time']:.2f}x"
        elif r['workers'] == 1 and r['sim_time'] > 0:
            speedup = "1.00x"
        else:
            speedup = "N/A"

        print(f"{r['workers']:>8} | {r['ticks']:>6} | {sim_str:>10} | {be_str:>10} | {total_str:>11} | {r['rows']:>7} | {speedup:>8}")

    print(f"{'='*90}")

    # Save results to CSV
    results_df = pd.DataFrame(results)
    results_filepath = 'testing_results.csv'
    results_df.to_csv(results_filepath, index=False)
    print(f"\nTesting results saved to {results_filepath}")

    return results


# Main function to run the simulation given thread count and tick count
def run_single(num_workers, num_ticks):
    """Run a single simulation pass with the given thread count and tick count."""
    server_proc = start_biosim_server()

    try:
        if num_workers == 1:
            all_rows, sim_time, per_config = run_all_simulations_sequential(num_ticks)
        else:
            all_rows, sim_time, per_config = run_all_simulations_threaded(num_workers, num_ticks)

        print(f"\n{'='*60}")
        print(f"  Simulation completed: {sim_time:.2f}s, {len(all_rows)} rows")
        print(f"{'='*60}")

        if len(all_rows) > 0:
            be_time = run_parameter_learning(all_rows, output_prefix=f"w{num_workers}_t{num_ticks}")
            print(f"\n  Total time: sim={sim_time:.2f}s + learning={be_time:.2f}s = {sim_time + be_time:.2f}s")
        elif len(all_rows) == 0:
            print("\n  No rows collected — skipping parameter learning")

    finally:
        stop_biosim_server(server_proc)


def main():
    parser = argparse.ArgumentParser(
        description="Threaded BioSim simulation runner with testing"
    )
    parser.add_argument('--workers', type=int, default=4,
                        help='Number of threads for simulation (default: 4)')
    parser.add_argument('--ticks', type=int, default=1000,
                        help='Number of simulation ticks (default: 1000)')
    parser.add_argument('--testing', action='store_true',
                        help='Run a full simulation across different thread and tick combinations')
    parser.add_argument('--testing-workers', type=str, default='1,2,4,6,8,9,10,12,14,16,18',
                        help='Comma-separated thread counts (default: 1,2,4,6,8,10,12,14,16)')
    parser.add_argument('--testing-ticks', type=str, default='500,1000',
                        help='Comma-separated tick counts (default: 500,1000)')


    args = parser.parse_args()

    if args.testing:
        worker_counts = [int(x.strip()) for x in args.testing_workers.split(',')]
        tick_counts = [int(x.strip()) for x in args.testing_ticks.split(',')]
        print(f"Running testing: workers={worker_counts}, ticks={tick_counts}")
        print(f"Total runs: {len(worker_counts) * len(tick_counts)}")
        run_testing(worker_counts, tick_counts)
    else:
        print(f"Running with {args.workers} worker(s), {args.ticks} ticks")
        run_single(args.workers, args.ticks)


if __name__ == '__main__':
    main()