
# learn_probabilities.py
# Author: Joshua Elston
# Last Edited: 03/04/2026
# Modified: 3/3/2026 - Multi-config support

# This script is used to create simulation runs of the IHab/HALO Gateway
# environment using the Biosim configuration files generated by TRACLabs.
# With the reduced subset of anomaly scenarios being modeled, the script
# then looks to perform parameter learning to inform the probabilities
# within the Bayesian network CPDs.

# Updated anomaly list to include relevant subgroups and "Unknown Anomaly"

# hatch open - true - 1
# hatch closed - false - 0

import os, json, subprocess, requests, time
import pandas as pd

from pgmpy.utils import get_example_model
print(get_example_model(model='alarm'))

from pgmpy.models import BayesianNetwork
from pgmpy.factors.discrete import TabularCPD
from reduced_network_structure import reduced_network
from reduced_prior_probabilities import reduced_prior_probabilities
from reduced_add_cpds import add_cpds

current_dir = os.path.dirname(os.path.abspath(__file__))
reduced_split_probability_dict = os.path.join(current_dir, "reduced_split_probabilities_dict.json")
reduced_hidden_probabilities_dict = os.path.join(current_dir, "reduced_hidden_probabilities_dict.json")
with open(reduced_split_probability_dict, "r") as file:
    reduced_split_probability_dict = json.load(file)
with open(reduced_hidden_probabilities_dict, "r") as file:
    reduced_hidden_probabilities_dict = json.load(file)

# Define the cardinality of each anomaly as 2, where 0 represents the anomaly not being present (False) and 1 represents the anomaly being present (True)
anomaly_cardinality = 2

# Create the Bayesian Network
model = BayesianNetwork(reduced_network)
print(model)

# NOTE: Can uncomment to view the reduced network as manually defined to compare learned
# probabilities with those input by hand
# prior_cpds_dict = {}

# # From the prior probabilities, add CPDs for the anomalies
# for anomaly, prior_probability in reduced_prior_probabilities.items():
#     model.add_cpds(TabularCPD(
#                             variable = anomaly, 
#                             variable_card = anomaly_cardinality, 
#                             values = [[1 - prior_probability], [prior_probability]] # ordered as [False, True]
#                             ))
#     prior_cpds_dict[anomaly] = {'False': 1 - prior_probability, 'True': prior_probability}

# # Add the CPDs for the parameters conditioned on multiple anomalies
# add_cpds(model, reduced_split_probability_dict, reduced_hidden_probabilities_dict, anomaly_cardinality, print_cpds=True)

print('you are here---')

# Configuration-to-Anomaly Mapping
# Resolve paths relative to this script's location so it works from any CWD
_mars_repos_dir = os.path.abspath(os.path.join(current_dir, '..', '..', '..', '..', '..'))
CONFIG_DIR = os.path.join(_mars_repos_dir, 'biosim-daphne', 'configuration')

CONFIG_ANOMALY_MAP = {
    # 'default.biosim':       {'anomaly': 'CDRA Failure (IHab)',                     'tick': 200},
    'low_o2_ihab.biosim':   {'anomaly': 'Emergency O2 System Maintenance (IHab)',  'tick': 200},
    'low_o2_halo.biosim':   {'anomaly': 'Emergency O2 System Maintenance (HALO)',  'tick': 200},
    'default_leak.biosim': {'anomaly': 'Loss of Pressure (IHab)',             'tick': 200,
                            'second_anomaly': 'Loss of Pressure (HALO)'},
    'high_co2_ihab.biosim': {'anomaly': 'Excess CO2 in Cabin (IHab)',              'tick': 200},
    'high_co2_halo.biosim': {'anomaly': 'Excess CO2 in Cabin (HALO)',              'tick': 200},
    # 'bio_filter.biosim':    {'anomaly': 'Biological Filter Saturation (IHab)',     'tick': 200,
    #                          'halo_anomaly': 'Biological Filter Saturation (Habitat)',
    #                          'halo_sensors': ['ppO2_HALO']},
    'bio_filter.biosim':    {'anomaly': 'Biological Filter Saturation',   'hatch_status': 'open', 'tick': 200},
    'bio_filter_ihab.biosim': {'anomaly': 'Biological Filter Saturation',  'hatch_status': 'closed',   'tick': 200},
    'high_humidity.biosim': {'anomaly': 'Unknown Anomaly',                         'tick': 200},
    'low_humidity.biosim':  {'anomaly': 'Unknown Anomaly',                         'tick': 0},
    'high_o2.biosim':       {'anomaly': 'Unknown Anomaly',                         'tick': 200},
    'high_pressure.biosim': {'anomaly': 'Unknown Anomaly',                         'tick': 200},
    # 'final_vccr.biosim':    {'anomaly': 'CDRA Failure (IHab)',                     'tick': 100,
    #                          'halo_anomaly': 'CDRA Failure (Habitat)',
    #                          'halo_sensors': ['ppCO2_HALO', 'Humidity_HALO']},
    'final_vccr.biosim':    {'anomaly': 'CDRA Failure', 'hatch_status': 'open',      'tick': 100},
    'default_vccr_ihab.biosim':    {'anomaly': 'CDRA Failure', 'hatch_status': 'closed', 'tick': 100},
    'low_co2.biosim':       {'anomaly': 'Unknown Anomaly',                         'tick': 0},

}

# Anomaly-to-Group Mapping
ANOMALY_GROUPS = {
    "Group 1": [
        "CDRA Failure",
        "Emergency O2 System Maintenance (IHab)",
        "Emergency O2 System Maintenance (HALO)",
        "Excess CO2 in Cabin (IHab)",
        "Excess CO2 in Cabin (HALO)",
    ],
    "Group 3": [
        "Biological Filter Saturation",
    ],
    "Group 7": [
        "Loss of Pressure (IHab)",
        "Loss of Pressure (HALO)",
    ],
}

# Anomaly symptom definitions: which sensors must be off-nominal and at what threshold.
# Threshold values: 1 = warning (caution) or above, 2 = critical only.
# "sensors" is a list of (sensor_column_name, min_threshold) tuples.
# ALL listed sensors must meet their threshold for the anomaly to be considered present.
ANOMALY_SYMPTOMS = {
    # CDRA Failure: ppO2 lower critical, ppCO2 upper critical, humidity above warning
    # "CDRA Failure (IHab)": {
    #     "component": "[HIDDEN] CDRA Failure Component",
    #     "sensors": [
    #         ("low ppO2_IHab (IHab)", 1),       # critical
    #         ("high ppCO2_IHab (IHab)", 2),      # critical
    #         ("high Humidity_IHab (IHab)", 1),    # warning or above
    #     ],
    # },
    "CDRA Failure": {
        "component": "[HIDDEN] CDRA Failure Component",
        # "hatch_open_sensors": [],
        # "hatch_closed_sensors": [],
        "sensors": [
            ("low ppO2_IHab (IHab)", 1),
            ("high ppCO2_IHab (IHab)", 2),
            ("high Humidity_IHab (IHab)", 1),
            ("low ppO2_HALO (HALO)", 1),
            ("high ppCO2_HALO (HALO)", 2),
            ("high Humidity_HALO (HALO)", 1),
        ],
    },
    # BFS: ppO2 exceeds lower caution, ppCO2 exceeds upper caution
    # "Biological Filter Saturation (IHab)": {
    #     "component": "[HIDDEN] BFS Component",
    #     "sensors": [
    #         ("low ppO2_IHab (IHab)", 1),        # warning or above
    #         ("high ppCO2_IHab (IHab)", 1),       # warning or above
    #     ],
    # },
    "Biological Filter Saturation": {
        "component": "[HIDDEN] BFS Component",
        "sensors": [
            ("low ppO2_IHab (IHab)", 1),
            ("high ppCO2_IHab (IHab)", 1),
            ("low ppO2_HALO (HALO)", 1),
            ("high ppCO2_HALO (HALO)", 1),
        ],
    },
    # Emergency O2: ppO2 exceeds lower caution
    "Emergency O2 System Maintenance (IHab)": {
        "component": "[HIDDEN] Emergency O2 System Maintenance Component",
        "sensors": [
            ("low ppO2_IHab (IHab)", 1),         # warning or above
        ],
    },
    "Emergency O2 System Maintenance (HALO)": {
        "component": "[HIDDEN] Emergency O2 System Maintenance Component",
        "sensors": [
            ("low ppO2_HALO (HALO)", 1),         # warning or above
        ],
    },
    # Excess CO2: ppCO2 exceeds critical
    "Excess CO2 in Cabin (IHab)": {
        "component": "[HIDDEN] Excess CO2 in Cabin Component",
        "sensors": [
            ("high ppCO2_IHab (IHab)", 2),       # critical only
        ],
    },
    "Excess CO2 in Cabin (HALO)": {
        "component": "[HIDDEN] Excess CO2 in Cabin Component",
        "sensors": [
            ("high ppCO2_HALO (HALO)", 2),       # critical only
        ],
    },
    # Loss of Pressure: ppO2, ppCO2, total pressure all below caution
    "Loss of Pressure (IHab)": {
        "component": "[HIDDEN] Loss of Pressure Component",
        "sensors": [
            ("low ppO2_IHab (IHab)", 1),
            ("low ppCO2_IHab (IHab)", 1),
            ("low Total_Cabin_Pressure_IHab (IHab)", 1),
        ],
    },
    "Loss of Pressure (HALO)": {
        "component": "[HIDDEN] Loss of Pressure Component",
        "sensors": [
            ("low ppO2_HALO (HALO)", 1),
            ("low ppCO2_HALO (HALO)", 1),
            ("low Total_Cabin_Pressure_HALO (HALO)", 1),
        ],
    },
}

# All anomaly names used in the Bayesian network
anomalies = ["Biological Filter Saturation", "CDRA Failure",
             "Emergency O2 System Maintenance (IHab)","Emergency O2 System Maintenance (HALO)",
             "Excess CO2 in Cabin (IHab)","Excess CO2 in Cabin (HALO)",
             "Loss of Pressure (IHab)", "Loss of Pressure (HALO)",
             "Unknown Anomaly", "Group 1", "Group 3", "Group 7"]

# Parameters
SERVER_URL = 'http://localhost:8009'
NUM_TICKS = 1000


def parse_simulation_ticks(data, anomaly_name, anomaly_tick, anomalies_list,
                          halo_anomaly=None, halo_sensors=None, second_anomaly=None, hatch_status=None):
    """
    Parse tick snapshots from a single simulation run into row dicts.
    
    Args:
        data: JSON response from the simulation log endpoint
        anomaly_name: The anomaly to inject for this config (or None for baseline)
        anomaly_tick: The tick number at which the anomaly activates (or None)
        anomalies_list: Full list of anomaly names used in the Bayesian network
        halo_anomaly: Optional habitat-wide anomaly name to inject when
                      specified HALO sensors show off-nominal values
        halo_sensors: List of HALO sensor name substrings to check for symptoms
                      (e.g. ['ppCO2_HALO', 'Humidity_HALO'] for CDRA,
                       ['ppO2_HALO'] for bio filter)
    
    Returns:
        List of row dicts suitable for DataFrame construction
    """
    from collections import defaultdict, deque
    history = defaultdict(lambda: deque(maxlen=30))
    rows = []

    for idx, tick in enumerate(data.get('ticks', [])):
        tick_num = tick.get('tick', idx)
        modules_state = tick.get('modules', {})
        sensor_row = {'tick': tick_num}

        param_names = []
        for mod_name, mod in modules_state.items():
            module_type = mod.get('moduleType', '')
            if "Sensor" in module_type:
                props = mod.get('properties', {})
                input_val = mod.get('input')
                if input_val is None:
                    if "_" in mod_name:
                        input_val = mod_name.split("_")[-1]
                    else:
                        input_val = ""
                base_name = f"{mod_name} ({input_val})"

                # Create two columns for split parameters
                high_param_name = f'high {base_name}'
                low_param_name = f'low {base_name}'
                # Create two columns for high/low (t-1) parameters
                prev_high_param_name = f'high {base_name} (t-1)'
                prev_low_param_name = f'low {base_name} (t-1)'

                param_names.extend([high_param_name, low_param_name, prev_high_param_name, prev_low_param_name])

                if 'value' in props:
                    sensor_value = props['value']

                    # Get the monitoring result
                    if "monitoringResult" in props:
                        result = props["monitoringResult"]
                        # Map levels for high and low parameters
                        sensor_row[high_param_name] = (
                            2 if 'CRITICAL_HIGH' in result else
                            1 if 'WARNING_HIGH' in result else 0
                        )
                        sensor_row[low_param_name] = (
                            2 if 'CRITICAL_LOW' in result else
                            1 if 'WARNING_LOW' in result else 0
                        )

                        # Get t-30 (t-1) result
                        history_queue = history[base_name]
                        if len(history_queue) >= 30:  # if length is 30, t-30 exists
                            t_minus_30_result = history_queue[0]
                            sensor_row[prev_high_param_name] = (
                                2 if 'CRITICAL_HIGH' in t_minus_30_result else
                                1 if 'WARNING_HIGH' in t_minus_30_result else 0
                            )
                            sensor_row[prev_low_param_name] = (
                                2 if 'CRITICAL_LOW' in t_minus_30_result else
                                1 if 'WARNING_LOW' in t_minus_30_result else 0
                            )
                        else:
                            sensor_row[prev_high_param_name] = 0
                            sensor_row[prev_low_param_name] = 0
                        # Append current result to history
                        history_queue.append(result)

                # Store all properties
                for prop_key, prop_val in props.items():
                    column_name = f"{base_name}_{prop_key}"
                    sensor_row[column_name] = prop_val


        if hatch_status is None or hatch_status == 'open':
            sensor_row['Hatch Status'] = 1
        elif hatch_status == 'closed':
            sensor_row['Hatch Status'] = 0  

        # --- Symptom-based anomaly injection ---
        # 1. Set hidden component = 1 at the malfunction tick
        if anomaly_name is not None and anomaly_tick is not None and tick_num is not None:
            if anomaly_name in ANOMALY_SYMPTOMS:
                comp = ANOMALY_SYMPTOMS[anomaly_name]["component"]
                sensor_row[comp] = int(tick_num >= anomaly_tick)
            # For second_anomaly (e.g., default_leak sets both IHab and HALO)
            if second_anomaly is not None and second_anomaly in ANOMALY_SYMPTOMS:
                comp2 = ANOMALY_SYMPTOMS[second_anomaly]["component"]
                sensor_row[comp2] = int(tick_num >= anomaly_tick)

        # 2. Set each anomaly = 1 only when its hidden component is active
        #    AND ALL expected symptoms meet their threshold.
        #    If component is active but symptoms have decayed, anomaly stays 0
        #    (Unknown Anomaly will catch it later).
        for anom_name, anom_info in ANOMALY_SYMPTOMS.items():
            comp_col = anom_info["component"]
            component_active = sensor_row.get(comp_col, 0) == 1
            if component_active:
                #///////////////////chamge here///////////////////////////////////
                ihab_sensors = []
                for i in anom_info["sensors"]:
                    if i[0].endswith("(IHab)"):
                        ihab_sensors.append(i)
                
                if hatch_status == 'open' or hatch_status is None:
                    all_symptoms_met = all(
                        sensor_row.get(sensor, 0) >= threshold
                        for sensor, threshold in anom_info["sensors"]
                    )

                elif hatch_status == 'closed':
                    all_symptoms_met = all(
                        sensor_row.get(sensor, 0) >= threshold 
                        for sensor, threshold in ihab_sensors)

                sensor_row[anom_name] = int(all_symptoms_met)
            else:
                sensor_row.setdefault(anom_name, 0)

        # Ensure all anomaly columns exist with default 0
        for anomaly in anomalies_list:
            sensor_row.setdefault(anomaly, 0)

        # Set group columns based on active anomalies
        for group_name, group_anomalies in ANOMALY_GROUPS.items():
            sensor_row[group_name] = int(any(
                sensor_row.get(a, 0) == 1 for a in group_anomalies
            ))

        # Check whether any known anomalies are present
        no_known_anomalies = all(sensor_row[anomaly] != 1 for anomaly in anomalies_list)
        # Check whether any parameter values are off-nominal
        no_active_params = all(sensor_row.get(param, 0) == 0 for param in param_names)

        if no_known_anomalies and not no_active_params:
            sensor_row['Unknown Anomaly'] = 1
        else:
            sensor_row['Unknown Anomaly'] = 0

        if no_known_anomalies and no_active_params:
            sensor_row['No Anomalies Present'] = 1
        else:
            sensor_row['No Anomalies Present'] = 0

        # Only store if sensor values are found
        if len(sensor_row) > 1:  # more than just tick
            rows.append(sensor_row)

    return rows


def run_simulation(server_url, config_path, num_ticks):
    """
    Start a simulation with the given config, advance it, and return the log data.
    
    Args:
        server_url: BioSim server URL
        config_path: Path to the .biosim config file
        num_ticks: Number of ticks to advance the simulation
    
    Returns:
        JSON log data from the simulation
    """
    # Read the config file
    with open(config_path, 'r') as f:
        biosim_xml = f.read()

    # Submit the XML config and get a simulation ID
    resp = requests.post(
        f'{server_url}/api/simulation/start',
        headers={'Content-Type': 'text/plain'},
        data=biosim_xml
    )
    if not resp.ok:
        raise RuntimeError(f"Failed to start simulation for {config_path}: {resp.status_code} {resp.text}")
    simID = resp.json()['simId']
    print(f"  Started BioSim simulation with {os.path.basename(config_path)}. Got simID: {simID}")

    # Advance simulation
    for i in range(num_ticks):
        resp = requests.post(f'{server_url}/api/simulation/{simID}/tick')
        time.sleep(0.02)  # small delay to avoid overwhelming the server
    print(f"  Advanced simulation {num_ticks} ticks.")

    # Fetch run log (all tick snapshots) <-- only works if tick logging is enabled with --writeTicks
    resp = requests.get(f'{server_url}/api/simulation/{simID}/log')
    if not resp.ok:
        raise RuntimeError(f"Failed to get simulation log for {config_path}: {resp.status_code} {resp.text}")

    data = resp.json()
    print(f"  Downloaded log with {len(data.get('ticks', []))} ticks.")
    return data


# Start Biosim simulation by calling java file (avoiding call to bash with 'bin')
jar_path = os.path.join(_mars_repos_dir, 'biosim', 'target', 'biosim-2.0.0-jar-with-dependencies.jar')
server_proc = subprocess.Popen(['java', '-jar', jar_path, '--writeTicks'])
print('Starting Biosim server...')

# Wait for server to start listening on port 8009
time.sleep(5)

# Collect rows from all simulation runs
all_rows = []

for config_name, config_info in CONFIG_ANOMALY_MAP.items():
    config_path = os.path.join(CONFIG_DIR, config_name)
    anomaly_name = config_info['anomaly']
    anomaly_tick = config_info['tick']
    hatch_status = config_info.get('hatch_status', None)

    print(f"\n{'='*60}")
    print(f"Running config: {config_name}")
    print(f"  Anomaly: {anomaly_name}")
    print(f"  Anomaly tick: {anomaly_tick}")
    print(f"{'='*60}")

    try:
        halo_anomaly = config_info.get('halo_anomaly', None)
        halo_sensors = config_info.get('halo_sensors', None)
        second_anomaly = config_info.get('second_anomaly', None)
        data = run_simulation(SERVER_URL, config_path, NUM_TICKS)
        rows = parse_simulation_ticks(data, anomaly_name, anomaly_tick, anomalies,
                                     halo_anomaly=halo_anomaly, halo_sensors=halo_sensors,
                                     second_anomaly=second_anomaly, hatch_status=hatch_status)
        print(f"  Parsed {len(rows)} rows from {config_name}")
        all_rows.extend(rows)
    except Exception as e:
        print(f"  ERROR running {config_name}: {e}")
        print(f"  Skipping this config and continuing...")
        continue

print(f"\n{'='*60}")
print(f"Total rows collected from all configs: {len(all_rows)}")
print(f"{'='*60}")


def get_ordered_bn_columns(all_nodes):
    sensors = ['ppCO2', 'ppO2', 'Humidity', 'Total_Cabin_Pressure']
    locations = ['HALO', 'IHab']
    # Parameter nodes
    param_nodes_ordered = []
    for sensor in sensors:
        for loc in locations:
            low = next((n for n in all_nodes if f'low {sensor} ({loc})' in n and '(t-1)' not in n), None)
            high = next((n for n in all_nodes if f'high {sensor} ({loc})' in n and '(t-1)' not in n), None)
            if low: param_nodes_ordered.append(low)
            if high: param_nodes_ordered.append(high)
    anomaly_nodes_ordered = [n for n in anomalies if n in all_nodes]
    other_nodes_ordered = [
        n for n in all_nodes if n not in param_nodes_ordered
                                 and n not in anomaly_nodes_ordered
                                 and not '[HIDDEN]' in n
    ]
    return param_nodes_ordered + anomaly_nodes_ordered + other_nodes_ordered

df_full = pd.DataFrame(all_rows)
print("Full dataset shape:", df_full.shape)
print(df_full.head())

# Save DataFrame for parameter learning
full_filepath = 'biosim_full.csv'
df_full.to_csv(full_filepath, index=False)
print('Saved full biosim dataset to', full_filepath)

# After all simulations, terminate server
server_proc.terminate()

# node_names = set(model.nodes()) # includes parameters, anomalies, and hidden parameters
# print(node_names)

# Extract relevant columns for parameter learning dataset
ordered_cols = get_ordered_bn_columns(model.nodes())
df_training = df_full[[col for col in ordered_cols if col in df_full.columns]]
print('Training dataset shape', df_training.shape)
print(df_training.head())
training_filepath = 'biosim_training_dataset.csv'
df_training.to_csv(training_filepath, index=False)
print('Saved training dataset to', training_filepath)

# Create samples from biosim training dataset
# samples = df_training.iloc[[30, 150, 250, 350, 450]]
samples = df_training
print(samples.head())

# Create blank model from which to learn new parameter probabilities
new_model = BayesianNetwork(ebunch=model.edges())

# Add hidden evidence as latent variables
latent_variables = []
for edge in model.edges:
    for node in edge:
        if '[HIDDEN]' in node:
            # print('Hidden parameter found at', node)
            if node not in latent_variables:
                latent_variables.append(node)
# print(latent_variables)

# Drop latent variables (if any) for Expectation Maximization input
samples_latent = samples.drop(latent_variables, errors='ignore')
# Build model using latents
model_latent = BayesianNetwork(model.edges(), latents=set(latent_variables))

from pgmpy.estimators import ExpectationMaximization as EM
em_est = EM(model_latent, data=samples_latent)
learned_cpds = em_est.get_parameters()
for cpd in learned_cpds:
    print(cpd)
with open('all_cpds.txt', 'w') as f:
    for cpd in learned_cpds:
        f.write(f"Variable: {cpd.variable}\n")
        f.write(f"Parents: {cpd.variables[1:]}\n")
        f.write(f"Values:\n{cpd.get_values()}\n\n")
model_latent.add_cpds(*learned_cpds)