
# learn_probabilities.py
# Author: Joshua Elston
# Last Edited: 03/04/2026
# Modified: 3/3/2026 - Multi-config support

# This script is used to create simulation runs of the IHab/HALO Gateway
# environment using the Biosim configuration files generated by TRACLabs.
# With the reduced subset of anomaly scenarios being modeled, the script
# then looks to perform parameter learning to inform the probabilities
# within the Bayesian network CPDs.

# Updated anomaly list to include relevant subgroups and "Unknown Anomaly"

# hatch open - true - 1
# hatch closed - false - 0

# Usage:
#   python learn_probabilities_threaded.py # default: 4 workers, 1000 ticks
#   python learn_probabilities_threaded.py --workers 14 --ticks 500 
#   python learn_probabilities_threaded.py --benchmark # run full testing accross different threads and ticks

import os, json, subprocess, requests, time, argparse, sys
import pandas as pd
from collections import defaultdict, deque
from concurrent.futures import ThreadPoolExecutor, as_completed
import threading

from pgmpy.models import BayesianNetwork
from reduced_network_structure import reduced_network


current_dir = os.path.dirname(os.path.abspath(__file__))
_mars_repos_dir = os.path.abspath(os.path.join(current_dir, '..', '..', '..', '..', '..'))
CONFIG_DIR = os.path.abspath(os.path.join(current_dir, 'configuration'))

reduced_split_probability_dict_path = os.path.join(current_dir, "reduced_split_probabilities_dict.json")
reduced_hidden_probabilities_dict_path = os.path.join(current_dir, "reduced_hidden_probabilities_dict.json")
with open(reduced_split_probability_dict_path, "r") as file:
    reduced_split_probability_dict = json.load(file)
with open(reduced_hidden_probabilities_dict_path, "r") as file:
    reduced_hidden_probabilities_dict = json.load(file)

# Create the Bayesian Network
model = BayesianNetwork(reduced_network)

SERVER_URL = 'http://localhost:8009'

# Lock to serialize simulation start requests 
_start_lock = threading.Lock()


CONFIG_ANOMALY_MAP = {
    'low_o2_ihab.biosim':   {'anomaly': 'Emergency O2 System Maintenance (IHab)',  'tick': 200},
    'low_o2_halo.biosim':   {'anomaly': 'Emergency O2 System Maintenance (HALO)',  'tick': 200},
    'default_leak.biosim': {'anomaly': 'Loss of Pressure (IHab)',             'tick': 200,
                            'second_anomaly': 'Loss of Pressure (HALO)'},
    'high_co2_ihab.biosim': {'anomaly': 'Excess CO2 in Cabin (IHab)',              'tick': 200},
    'high_co2_halo.biosim': {'anomaly': 'Excess CO2 in Cabin (HALO)',              'tick': 200},
    'bio_filter.biosim':    {'anomaly': 'Biological Filter Saturation',   'hatch_status': 'open', 'tick': 200},
    'bio_filter_ihab.biosim': {'anomaly': 'Biological Filter Saturation',  'hatch_status': 'closed',   'tick': 200},
    'high_humidity.biosim': {'anomaly': 'Unknown Anomaly',                         'tick': 200},
    'low_humidity.biosim':  {'anomaly': 'Unknown Anomaly',                         'tick': 0},
    'high_o2.biosim':       {'anomaly': 'Unknown Anomaly',                         'tick': 200},
    'high_pressure.biosim': {'anomaly': 'Unknown Anomaly',                         'tick': 200},
    'final_vccr.biosim':    {'anomaly': 'CDRA Failure', 'hatch_status': 'open',      'tick': 100},
    'default_vccr_ihab.biosim':    {'anomaly': 'CDRA Failure', 'hatch_status': 'closed', 'tick': 100},
    'low_co2.biosim':       {'anomaly': 'Unknown Anomaly',                         'tick': 0},
}

ANOMALY_GROUPS = {
    "Group 1": [
        "CDRA Failure",
        "Emergency O2 System Maintenance (IHab)",
        "Emergency O2 System Maintenance (HALO)",
        "Excess CO2 in Cabin (IHab)",
        "Excess CO2 in Cabin (HALO)",
    ],
    "Group 3": [
        "Biological Filter Saturation",
    ],
    "Group 7": [
        "Loss of Pressure (IHab)",
        "Loss of Pressure (HALO)",
    ],
}

ANOMALY_SYMPTOMS = {
    "CDRA Failure": {
        "component": "[HIDDEN] CDRA Failure Component",
        "sensors": [
            ("low ppO2_IHab (IHab)", 1),
            ("high ppCO2_IHab (IHab)", 2),
            ("high Humidity_IHab (IHab)", 1),
            ("low ppO2_HALO (HALO)", 1),
            ("high ppCO2_HALO (HALO)", 2),
            ("high Humidity_HALO (HALO)", 1),
        ],
    },
    "Biological Filter Saturation": {
        "component": "[HIDDEN] BFS Component",
        "sensors": [
            ("low ppO2_IHab (IHab)", 1),
            ("high ppCO2_IHab (IHab)", 1),
            ("low ppO2_HALO (HALO)", 1),
            ("high ppCO2_HALO (HALO)", 1),
        ],
    },
    "Emergency O2 System Maintenance (IHab)": {
        "component": "[HIDDEN] Emergency O2 System Maintenance Component",
        "sensors": [
            ("low ppO2_IHab (IHab)", 1),
        ],
    },
    "Emergency O2 System Maintenance (HALO)": {
        "component": "[HIDDEN] Emergency O2 System Maintenance Component",
        "sensors": [
            ("low ppO2_HALO (HALO)", 1),
        ],
    },
    "Excess CO2 in Cabin (IHab)": {
        "component": "[HIDDEN] Excess CO2 in Cabin Component",
        "sensors": [
            ("high ppCO2_IHab (IHab)", 2),
        ],
    },
    "Excess CO2 in Cabin (HALO)": {
        "component": "[HIDDEN] Excess CO2 in Cabin Component",
        "sensors": [
            ("high ppCO2_HALO (HALO)", 2),
        ],
    },
    "Loss of Pressure (IHab)": {
        "component": "[HIDDEN] Loss of Pressure Component",
        "sensors": [
            ("low ppO2_IHab (IHab)", 1),
            ("low ppCO2_IHab (IHab)", 1),
            ("low Total_Cabin_Pressure_IHab (IHab)", 1),
        ],
    },
    "Loss of Pressure (HALO)": {
        "component": "[HIDDEN] Loss of Pressure Component",
        "sensors": [
            ("low ppO2_HALO (HALO)", 1),
            ("low ppCO2_HALO (HALO)", 1),
            ("low Total_Cabin_Pressure_HALO (HALO)", 1),
        ],
    },
}

anomalies = ["Biological Filter Saturation", "CDRA Failure",
             "Emergency O2 System Maintenance (IHab)","Emergency O2 System Maintenance (HALO)",
             "Excess CO2 in Cabin (IHab)","Excess CO2 in Cabin (HALO)",
             "Loss of Pressure (IHab)", "Loss of Pressure (HALO)",
             "Unknown Anomaly", "Group 1", "Group 3", "Group 7"]


def parse_simulation_ticks(data, anomaly_name, anomaly_tick, anomalies_list,
                          halo_anomaly=None, halo_sensors=None, second_anomaly=None, hatch_status=None):
    """Parse tick snapshots from a single simulation run into row dicts."""
    history = defaultdict(lambda: deque(maxlen=30))
    rows = []

    for idx, tick in enumerate(data.get('ticks', [])):
        tick_num = tick.get('tick', idx)
        modules_state = tick.get('modules', {})
        sensor_row = {'tick': tick_num}

        param_names = []
        for mod_name, mod in modules_state.items():
            module_type = mod.get('moduleType', '')
            if "Sensor" in module_type:
                props = mod.get('properties', {})
                input_val = mod.get('input')
                if input_val is None:
                    if "_" in mod_name:
                        input_val = mod_name.split("_")[-1]
                    else:
                        input_val = ""
                base_name = f"{mod_name} ({input_val})"

                high_param_name = f'high {base_name}'
                low_param_name = f'low {base_name}'
                prev_high_param_name = f'high {base_name} (t-1)'
                prev_low_param_name = f'low {base_name} (t-1)'

                param_names.extend([high_param_name, low_param_name, prev_high_param_name, prev_low_param_name])

                if 'value' in props:
                    if "monitoringResult" in props:
                        result = props["monitoringResult"]
                        sensor_row[high_param_name] = (
                            2 if 'CRITICAL_HIGH' in result else
                            1 if 'WARNING_HIGH' in result else 0
                        )
                        sensor_row[low_param_name] = (
                            2 if 'CRITICAL_LOW' in result else
                            1 if 'WARNING_LOW' in result else 0
                        )

                        history_queue = history[base_name]
                        if len(history_queue) >= 30:
                            t_minus_30_result = history_queue[0]
                            sensor_row[prev_high_param_name] = (
                                2 if 'CRITICAL_HIGH' in t_minus_30_result else
                                1 if 'WARNING_HIGH' in t_minus_30_result else 0
                            )
                            sensor_row[prev_low_param_name] = (
                                2 if 'CRITICAL_LOW' in t_minus_30_result else
                                1 if 'WARNING_LOW' in t_minus_30_result else 0
                            )
                        else:
                            sensor_row[prev_high_param_name] = 0
                            sensor_row[prev_low_param_name] = 0
                        history_queue.append(result)

                for prop_key, prop_val in props.items():
                    column_name = f"{base_name}_{prop_key}"
                    sensor_row[column_name] = prop_val

        if hatch_status is None or hatch_status == 'open':
            sensor_row['Hatch Status'] = 1
        elif hatch_status == 'closed':
            sensor_row['Hatch Status'] = 0

        # Symptom-based anomaly injection
        if anomaly_name is not None and anomaly_tick is not None and tick_num is not None:
            if anomaly_name in ANOMALY_SYMPTOMS:
                comp = ANOMALY_SYMPTOMS[anomaly_name]["component"]
                sensor_row[comp] = int(tick_num >= anomaly_tick)
            if second_anomaly is not None and second_anomaly in ANOMALY_SYMPTOMS:
                comp2 = ANOMALY_SYMPTOMS[second_anomaly]["component"]
                sensor_row[comp2] = int(tick_num >= anomaly_tick)

        for anom_name, anom_info in ANOMALY_SYMPTOMS.items():
            comp_col = anom_info["component"]
            component_active = sensor_row.get(comp_col, 0) == 1
            if component_active:
                ihab_sensors = []
                for i in anom_info["sensors"]:
                    if i[0].endswith("(IHab)"):
                        ihab_sensors.append(i)

                if hatch_status == 'open' or hatch_status is None:
                    all_symptoms_met = all(
                        sensor_row.get(sensor, 0) >= threshold
                        for sensor, threshold in anom_info["sensors"]
                    )
                elif hatch_status == 'closed':
                    all_symptoms_met = all(
                        sensor_row.get(sensor, 0) >= threshold
                        for sensor, threshold in ihab_sensors)

                sensor_row[anom_name] = int(all_symptoms_met)
            else:
                sensor_row.setdefault(anom_name, 0)

        for anomaly in anomalies_list:
            sensor_row.setdefault(anomaly, 0)

        for group_name, group_anomalies in ANOMALY_GROUPS.items():
            sensor_row[group_name] = int(any(
                sensor_row.get(a, 0) == 1 for a in group_anomalies
            ))

        no_known_anomalies = all(sensor_row[anomaly] != 1 for anomaly in anomalies_list)
        no_active_params = all(sensor_row.get(param, 0) == 0 for param in param_names)

        if no_known_anomalies and not no_active_params:
            sensor_row['Unknown Anomaly'] = 1
        else:
            sensor_row['Unknown Anomaly'] = 0

        if no_known_anomalies and no_active_params:
            sensor_row['No Anomalies Present'] = 1
        else:
            sensor_row['No Anomalies Present'] = 0

        if len(sensor_row) > 1:
            rows.append(sensor_row)

    return rows


def run_simulation(server_url, config_path, num_ticks):
    """Start a simulation with the given config, advance it, and return the log data."""
    with open(config_path, 'r') as f:
        biosim_xml = f.read()

    # lock for the start call
    with _start_lock:
        resp = requests.post(
            f'{server_url}/api/simulation/start',
            headers={'Content-Type': 'text/plain'},
            data=biosim_xml
        )
        if not resp.ok:
            raise RuntimeError(f"Failed to start simulation for {config_path}: {resp.status_code} {resp.text}")
        simID = resp.json()['simId']
        print(f"    Started {os.path.basename(config_path)} → simID={simID}")

    # Tick advancement runs outside the lock
    for i in range(num_ticks):
        resp = requests.post(f'{server_url}/api/simulation/{simID}/tick')
        time.sleep(0.02)

    resp = requests.get(f'{server_url}/api/simulation/{simID}/log')
    if not resp.ok:
        raise RuntimeError(f"Failed to get simulation log for {config_path}: {resp.status_code} {resp.text}")

    data = resp.json()
    return data


def run_single_config(config_name, config_info, server_url, num_ticks):
    """
    Run a single simulation config end-to-end: simulate + parse.
    Returns (config_name, rows, elapsed_seconds).
    Thread-safe — no shared mutable state.
    """
    t0 = time.time()
    config_path = os.path.join(CONFIG_DIR, config_name)
    anomaly_name = config_info['anomaly']
    anomaly_tick = config_info['tick']
    hatch_status = config_info.get('hatch_status', None)
    halo_anomaly = config_info.get('halo_anomaly', None)
    halo_sensors = config_info.get('halo_sensors', None)
    second_anomaly = config_info.get('second_anomaly', None)

    data = run_simulation(server_url, config_path, num_ticks)
    rows = parse_simulation_ticks(data, anomaly_name, anomaly_tick, anomalies,
                                 halo_anomaly=halo_anomaly, halo_sensors=halo_sensors,
                                 second_anomaly=second_anomaly, hatch_status=hatch_status)
    elapsed = time.time() - t0
    return config_name, rows, elapsed


def get_ordered_bn_columns(all_nodes):
    sensors = ['ppCO2', 'ppO2', 'Humidity', 'Total_Cabin_Pressure']
    locations = ['HALO', 'IHab']
    param_nodes_ordered = []
    for sensor in sensors:
        for loc in locations:
            low = next((n for n in all_nodes if f'low {sensor} ({loc})' in n and '(t-1)' not in n), None)
            high = next((n for n in all_nodes if f'high {sensor} ({loc})' in n and '(t-1)' not in n), None)
            if low: param_nodes_ordered.append(low)
            if high: param_nodes_ordered.append(high)
    anomaly_nodes_ordered = [n for n in anomalies if n in all_nodes]
    other_nodes_ordered = [
        n for n in all_nodes if n not in param_nodes_ordered
                                 and n not in anomaly_nodes_ordered
                                 and not '[HIDDEN]' in n
    ]
    return param_nodes_ordered + anomaly_nodes_ordered + other_nodes_ordered


# Run simulation with threads
def run_all_simulations_threaded(max_workers, num_ticks, server_url=SERVER_URL):
    """
    Run all configs in parallel using ThreadPoolExecutor.
    Returns (all_rows, total_elapsed, per_config_times).
    """
    all_rows = []
    per_config_times = {}

    t_total_start = time.time()

    with ThreadPoolExecutor(max_workers=max_workers) as executor:
        futures = {
            executor.submit(run_single_config, name, info, server_url, num_ticks): name
            for name, info in CONFIG_ANOMALY_MAP.items()
        }

        for future in as_completed(futures):
            config_name = futures[future]
            try:
                name, rows, elapsed = future.result()
                per_config_times[name] = elapsed
                all_rows.extend(rows)
                print(f"  [Thread] {name}: {len(rows)} rows in {elapsed:.2f}s")
            except Exception as e:
                per_config_times[config_name] = -1
                print(f"  [Thread] ERROR {config_name}: {e}")

    total_elapsed = time.time() - t_total_start
    return all_rows, total_elapsed, per_config_times

# Run simulation without threads
def run_all_simulations_sequential(num_ticks, server_url=SERVER_URL):
    """
    Run all configs sequentially (baseline for comparison).
    Returns (all_rows, total_elapsed, per_config_times).
    """
    all_rows = []
    per_config_times = {}

    t_total_start = time.time()

    for config_name, config_info in CONFIG_ANOMALY_MAP.items():
        try:
            name, rows, elapsed = run_single_config(config_name, config_info, server_url, num_ticks)
            per_config_times[name] = elapsed
            all_rows.extend(rows)
            print(f"  [Sequential] {name}: {len(rows)} rows in {elapsed:.2f}s")
        except Exception as e:
            per_config_times[config_name] = -1
            print(f"  [Sequential] ERROR {config_name}: {e}")

    total_elapsed = time.time() - t_total_start
    return all_rows, total_elapsed, per_config_times


# Function for Parameter learning and saving the CPDs to a file
def run_parameter_learning(all_rows, output_prefix="threaded"):
    """Run EM parameter learning on collected simulation data."""
    from pgmpy.estimators import ExpectationMaximization as EM

    t0 = time.time()

    df_full = pd.DataFrame(all_rows)
    print(f"\nFull dataset shape: {df_full.shape}")

    full_filepath = f'biosim_full_{output_prefix}.csv'
    df_full.to_csv(full_filepath, index=False)
    print(f'Saved full biosim dataset to {full_filepath}')

    ordered_cols = get_ordered_bn_columns(model.nodes())
    df_training = df_full[[col for col in ordered_cols if col in df_full.columns]]
    print(f'Training dataset shape: {df_training.shape}')

    training_filepath = f'biosim_training_dataset_{output_prefix}.csv'
    df_training.to_csv(training_filepath, index=False)
    print(f'Saved training dataset to {training_filepath}')

    samples = df_training

    # Identify latent variables
    latent_variables = []
    for edge in model.edges:
        for node in edge:
            if '[HIDDEN]' in node:
                if node not in latent_variables:
                    latent_variables.append(node)

    samples_latent = samples.drop(latent_variables, errors='ignore')
    model_latent = BayesianNetwork(model.edges(), latents=set(latent_variables))

    em_est = EM(model_latent, data=samples_latent)
    learned_cpds = em_est.get_parameters()

    cpd_filepath = f'all_cpds_{output_prefix}.txt'
    with open(cpd_filepath, 'w') as f:
        for cpd in learned_cpds:
            f.write(f"Variable: {cpd.variable}\n")
            f.write(f"Parents: {cpd.variables[1:]}\n")
            f.write(f"Values:\n{cpd.get_values()}\n\n")
    print(f'Saved CPDs to {cpd_filepath}')

    model_latent.add_cpds(*learned_cpds)

    em_elapsed = time.time() - t0
    print(f'Parameter learning took {em_elapsed:.2f}s')
    return em_elapsed


def start_biosim_server():
    """Start the BioSim Java server and wait for it to be ready."""
    jar_path = os.path.join(_mars_repos_dir, 'biosim', 'target', 'biosim-2.0.0-jar-with-dependencies.jar')
    proc = subprocess.Popen(['java', '-jar', jar_path, '--writeTicks'])
    print('Starting BioSim server...')

    for attempt in range(30):
        try:
            resp = requests.get(f'{SERVER_URL}/api/simulation', timeout=2)
            if resp.ok:
                print(f'BioSim server ready after {attempt + 1}s')
                return proc
        except requests.ConnectionError:
            pass
        time.sleep(1)

    print('Warning: BioSim server may not be ready, proceeding anyway...')
    return proc


def stop_biosim_server(proc):
    """Terminate the BioSim server."""
    if proc:
        proc.terminate()
        proc.wait(timeout=10)
        print('BioSim server stopped.')


# Testing: run tests across different thread counts and tick counts
def run_testing(worker_counts, tick_counts):
    """
    Run simulations across all combinations of worker_counts and tick_counts.
    Collects timing data and prints a summary table.
    """
    results = []  # list of dicts: {workers, ticks, total_time, sim_time, em_time, rows}

    for num_ticks in tick_counts:
        for num_workers in worker_counts:
            label = f"sequential" if num_workers == 1 else f"{num_workers} threads"
            print(f"\n{'='*70}")
            print(f"  TESTING: {label}, {num_ticks} ticks")
            print(f"{'='*70}")

            server_proc = start_biosim_server()

            try:
                t_run_start = time.time()

                if num_workers == 1:
                    all_rows, sim_time, per_config = run_all_simulations_sequential(num_ticks)
                else:
                    all_rows, sim_time, per_config = run_all_simulations_threaded(num_workers, num_ticks)

                num_rows = len(all_rows)
                print(f"\n  Simulation phase: {sim_time:.2f}s, {num_rows} rows collected")

                # Run EM learning
                if num_rows > 0:
                    em_time = run_parameter_learning(all_rows, output_prefix=f"w{num_workers}_t{num_ticks}")
                else:
                    em_time = 0.0
                    print("  Skipping EM learning (no data)")

                total_time = time.time() - t_run_start

                results.append({
                    'workers': num_workers,
                    'ticks': num_ticks,
                    'sim_time': sim_time,
                    'em_time': em_time,
                    'total_time': total_time,
                    'rows': num_rows,
                    'configs': len(CONFIG_ANOMALY_MAP),
                })

            except Exception as e:
                print(f"  TESTING ERROR: {e}")
                results.append({
                    'workers': num_workers,
                    'ticks': num_ticks,
                    'sim_time': -1,
                    'em_time': -1,
                    'total_time': -1,
                    'rows': 0,
                    'configs': len(CONFIG_ANOMALY_MAP),
                })
            finally:
                stop_biosim_server(server_proc)
                time.sleep(3)  # give port time to free up

    # Print summary table
    print(f"\n\n{'='*90}")
    print(f"  TESTING RESULTS SUMMARY")
    print(f"{'='*90}")
    print(f"{'Workers':>8} | {'Ticks':>6} | {'Sim Time':>10} | {'EM Time':>10} | {'Total Time':>11} | {'Rows':>7} | {'Speedup':>8}")
    print(f"{'-'*8}-+-{'-'*6}-+-{'-'*10}-+-{'-'*10}-+-{'-'*11}-+-{'-'*7}-+-{'-'*8}")

    # sequential times for speedup calculation
    baseline_times = {}
    for r in results:
        if r['workers'] == 1 and r['sim_time'] > 0:
            baseline_times[r['ticks']] = r['sim_time']

    for r in results:
        sim_str = f"{r['sim_time']:.2f}s" if r['sim_time'] >= 0 else "ERROR"
        em_str = f"{r['em_time']:.2f}s" if r['em_time'] >= 0 else "ERROR"
        total_str = f"{r['total_time']:.2f}s" if r['total_time'] >= 0 else "ERROR"

        baseline = baseline_times.get(r['ticks'], None)
        if baseline and r['sim_time'] > 0:
            speedup = f"{baseline / r['sim_time']:.2f}x"
        elif r['workers'] == 1 and r['sim_time'] > 0:
            speedup = "1.00x"
        else:
            speedup = "N/A"

        print(f"{r['workers']:>8} | {r['ticks']:>6} | {sim_str:>10} | {em_str:>10} | {total_str:>11} | {r['rows']:>7} | {speedup:>8}")

    print(f"{'='*90}")

    # Save results to CSV
    results_df = pd.DataFrame(results)
    results_filepath = 'testing_results.csv'
    results_df.to_csv(results_filepath, index=False)
    print(f"\nTesting results saved to {results_filepath}")

    return results


# Main function to run the simulation given thread count and tick count
def run_single(num_workers, num_ticks):
    """Run a single simulation pass with the given thread count and tick count."""
    server_proc = start_biosim_server()

    try:
        if num_workers == 1:
            all_rows, sim_time, per_config = run_all_simulations_sequential(num_ticks)
        else:
            all_rows, sim_time, per_config = run_all_simulations_threaded(num_workers, num_ticks)

        print(f"\n{'='*60}")
        print(f"  Simulation completed: {sim_time:.2f}s, {len(all_rows)} rows")
        print(f"{'='*60}")

        if len(all_rows) > 0:
            em_time = run_parameter_learning(all_rows, output_prefix=f"w{num_workers}_t{num_ticks}")
            print(f"\n  Total time: sim={sim_time:.2f}s + learning={em_time:.2f}s = {sim_time + em_time:.2f}s")
        elif len(all_rows) == 0:
            print("\n  No rows collected — skipping parameter learning")

    finally:
        stop_biosim_server(server_proc)

def main():
    parser = argparse.ArgumentParser(
        description="Threaded BioSim simulation runner with testing"
    )
    parser.add_argument('--workers', type=int, default=4,
                        help='Number of threads for simulation (default: 4)')
    parser.add_argument('--ticks', type=int, default=1000,
                        help='Number of simulation ticks (default: 1000)')
    parser.add_argument('--testing', action='store_true',
                        help='Run a full simulation across different thread and tick combinations')
    parser.add_argument('--testing-workers', type=str, default='1,2,4,6,8,12,14,16',
                        help='Comma-separated thread counts (default: 1,2,4,6,8,12,14,16)')
    parser.add_argument('--testing-ticks', type=str, default='500,1000',
                        help='Comma-separated tick counts (default: 500,1000)')


    args = parser.parse_args()

    if args.testing:
        worker_counts = [int(x.strip()) for x in args.testing_workers.split(',')]
        tick_counts = [int(x.strip()) for x in args.testing_ticks.split(',')]
        print(f"Running testing: workers={worker_counts}, ticks={tick_counts}")
        print(f"Total runs: {len(worker_counts) * len(tick_counts)}")
        run_testing(worker_counts, tick_counts)
    else:
        print(f"Running with {args.workers} worker(s), {args.ticks} ticks")
        run_single(args.workers, args.ticks)


if __name__ == '__main__':
    main()
