# learn_probabilities_threaded.py
# Author: Joshua Elston, Mahima Ganni
# Last Edited: 04/13/2026

# This script is used to create simulation runs of the IHab/HALO Gateway
# environment using the Biosim configuration files generated by TRACLabs.
# With the reduced subset of anomaly scenarios being modeled, the script
# then looks to perform parameter learning to inform the probabilities
# within the Bayesian network CPDs.

# Updated anomaly list to include relevant subgroups and "Unknown Anomaly", and updated anomalies
# with symptoms in both modules to measure whether the hatch between the modules is open (1, True)
# or closed (False, 0)
# Supports running multiple config files in a given run
# Parameter learning mechanism updated to Bayesian Estimation using Dirichlet priors
# (seeking to resolve uniform distributions issue observed using Expectation Maximization)
# Able to perform parameter learning in parallel to reduce training time
# Updated to only perform parameter learning on a subset of the nodes in the network (excluding
# group-level and unknown anomaly nodes, which are predefined and deterministic)
# Also updated 'Hatch Status' to more accurately-defined 'Fan Status' (1='on', 0='off'), that is
# now a parent of module-specific parameters

# Usage:
#   python learn_probabilities_threaded.py # default: 4 workers, 1000 ticks
#   python learn_probabilities_threaded.py --workers 14 --ticks 500 
#   python learn_probabilities_threaded.py --benchmark # run full testing across different threads and ticks

import os, json, subprocess, requests, time, argparse, sys
import pandas as pd
from collections import defaultdict, deque
from concurrent.futures import ThreadPoolExecutor, as_completed
import threading
from math import prod

from pgmpy.models import BayesianNetwork
from reduced_network_structure import reduced_network
from reduced_known_probabilities import known_cpds

current_dir = os.path.dirname(os.path.abspath(__file__))
_mars_repos_dir = os.path.abspath(os.path.join(current_dir, '..', '..', '..', '..', '..'))
CONFIG_DIR = os.path.abspath(os.path.join(current_dir, 'configuration'))

reduced_split_probability_dict_path = os.path.join(current_dir, "reduced_split_probabilities_dict.json")
reduced_hidden_probabilities_dict_path = os.path.join(current_dir, "reduced_hidden_probabilities_dict.json")
with open(reduced_split_probability_dict_path, "r") as file:
    reduced_split_probability_dict = json.load(file)
with open(reduced_hidden_probabilities_dict_path, "r") as file:
    reduced_hidden_probabilities_dict = json.load(file)

# Create the Bayesian Network
model = BayesianNetwork(reduced_network)

SERVER_URL = 'http://localhost:8009'

# Lock to serialize simulation start requests 
_start_lock = threading.Lock()


CONFIG_ANOMALY_MAP = {
    'low_o2_ihab.biosim':   {'anomaly': 'Emergency O2 System Maintenance (IHab)',  'tick': 200},
    'low_o2_halo.biosim':   {'anomaly': 'Emergency O2 System Maintenance (HALO)',  'tick': 200},
    'default_leak_ihab.biosim':   {'anomaly': 'Loss of Pressure (IHab)',  'tick': 200},
    'default_leak_halo.biosim':   {'anomaly': 'Loss of Pressure (HALO)',  'tick': 200},
    # 'default_leak.biosim': {'anomaly': 'Loss of Pressure (IHab)',             'tick': 200,
    #                         'second_anomaly': 'Loss of Pressure (HALO)'},
    'high_co2_ihab.biosim': {'anomaly': 'Excess CO2 in Cabin (IHab)',              'tick': 200},
    'high_co2_halo.biosim': {'anomaly': 'Excess CO2 in Cabin (HALO)',              'tick': 200},
    'bio_filter.biosim':    {'anomaly': 'Biological Filter Saturation',   'fan_status': 'on', 'tick': 200},
    'bio_filter_ihab.biosim': {'anomaly': 'Biological Filter Saturation',  'fan_status': 'off',   'tick': 200},
    'high_humidity.biosim': {'anomaly': 'Unknown Anomaly',                         'tick': 200},
    'low_humidity.biosim':  {'anomaly': 'Unknown Anomaly',                         'tick': 0},
    'high_o2.biosim':       {'anomaly': 'Unknown Anomaly',                         'tick': 200},
    'high_pressure.biosim': {'anomaly': 'Unknown Anomaly',                         'tick': 200},
    'final_vccr.biosim':    {'anomaly': 'CDRA Failure', 'fan_status': 'on',      'tick': 200},
    'default_vccr_ihab.biosim':    {'anomaly': 'CDRA Failure', 'fan_status': 'off', 'tick': 200},
    'low_co2.biosim':       {'anomaly': 'Unknown Anomaly',                         'tick': 0},
}

ANOMALY_GROUPS = {
    "Group 1": [
        "CDRA Failure",
        "Emergency O2 System Maintenance (IHab)",
        "Emergency O2 System Maintenance (HALO)",
        "Excess CO2 in Cabin (IHab)",
        "Excess CO2 in Cabin (HALO)",
    ],
    "Group 3": [
        "Biological Filter Saturation",
    ],
    "Group 7": [
        "Loss of Pressure (IHab)",
        "Loss of Pressure (HALO)",
    ],
}

# Anomaly symptom definitions: which sensors must be off-nominal and at what threshold.
# Threshold values: 1 = warning (caution) or above, 2 = critical only.
# "sensors" is a list of (sensor_column_name, min_threshold) tuples.
# ALL listed sensors must meet their threshold for the anomaly to be considered present.
ANOMALY_SYMPTOMS = {
    "CDRA Failure": {
        "component": "[HIDDEN] CDRA Failure Component",
        "sensors": [
            ("low ppO2_IHab (IHab)", 1),
            ("high ppCO2_IHab (IHab)", 2),
            ("high Humidity_IHab (IHab)", 1),
            ("low ppO2_HALO (HALO)", 1),
            ("high ppCO2_HALO (HALO)", 2),
            ("high Humidity_HALO (HALO)", 1),
        ],
    },
    "Biological Filter Saturation": {
        "component": "[HIDDEN] BFS Component",
        "sensors": [
            ("low ppO2_IHab (IHab)", 1),
            ("high ppCO2_IHab (IHab)", 1),
            ("low ppO2_HALO (HALO)", 1),
            ("high ppCO2_HALO (HALO)", 1),
        ],
    },
    "Emergency O2 System Maintenance (IHab)": {
        "component": "[HIDDEN] Emergency O2 System Maintenance Component",
        "sensors": [
            ("low ppO2_IHab (IHab)", 1),
        ],
    },
    "Emergency O2 System Maintenance (HALO)": {
        "component": "[HIDDEN] Emergency O2 System Maintenance Component",
        "sensors": [
            ("low ppO2_HALO (HALO)", 1),
        ],
    },
    "Excess CO2 in Cabin (IHab)": {
        "component": "[HIDDEN] Excess CO2 in Cabin Component",
        "sensors": [
            ("high ppCO2_IHab (IHab)", 2),
        ],
    },
    "Excess CO2 in Cabin (HALO)": {
        "component": "[HIDDEN] Excess CO2 in Cabin Component",
        "sensors": [
            ("high ppCO2_HALO (HALO)", 2),
        ],
    },
    "Loss of Pressure (IHab)": {
        "component": "[HIDDEN] Loss of Pressure Component",
        "sensors": [
            ("low ppO2_IHab (IHab)", 1),
            ("low ppCO2_IHab (IHab)", 1),
            ("low Total_Cabin_Pressure_IHab (IHab)", 1),
        ],
    },
    "Loss of Pressure (HALO)": {
        "component": "[HIDDEN] Loss of Pressure Component",
        "sensors": [
            ("low ppO2_HALO (HALO)", 1),
            ("low ppCO2_HALO (HALO)", 1),
            ("low Total_Cabin_Pressure_HALO (HALO)", 1),
        ],
    },
}

# All anomaly names used in the Bayesian network
anomalies = ["Biological Filter Saturation", "CDRA Failure",
             "Emergency O2 System Maintenance (IHab)","Emergency O2 System Maintenance (HALO)",
             "Excess CO2 in Cabin (IHab)","Excess CO2 in Cabin (HALO)",
             "Loss of Pressure (IHab)", "Loss of Pressure (HALO)",
             "Unknown Anomaly", "Group 1", "Group 3", "Group 7"]


def parse_simulation_ticks(data, anomaly_name, anomaly_tick, anomalies_list,
                          halo_anomaly=None, halo_sensors=None, second_anomaly=None, fan_status=None):
    """
    Parse tick snapshots from a single simulation run into row dicts.
    
    Args:
        data: JSON response from the simulation log endpoint
        anomaly_name: The anomaly to inject for this config (or None for baseline)
        anomaly_tick: The tick number at which the anomaly activates (or None)
        anomalies_list: Full list of anomaly names used in the Bayesian network
        halo_anomaly: Optional habitat-wide anomaly name to inject when
                      specified HALO sensors show off-nominal values
        halo_sensors: List of HALO sensor name substrings to check for symptoms
                      (e.g. ['ppCO2_HALO', 'Humidity_HALO'] for CDRA,
                       ['ppO2_HALO'] for bio filter)
    
    Returns:
        List of row dicts suitable for DataFrame construction
    """
    
    history = defaultdict(lambda: deque(maxlen=30))
    rows = []

    for idx, tick in enumerate(data.get('ticks', [])):
        tick_num = tick.get('tick', idx)
        modules_state = tick.get('modules', {})
        sensor_row = {'tick': tick_num}

        param_names = []
        for mod_name, mod in modules_state.items():
            module_type = mod.get('moduleType', '')
            if "Sensor" in module_type:
                props = mod.get('properties', {})
                input_val = mod.get('input')
                if input_val is None:
                    if "_" in mod_name:
                        input_val = mod_name.split("_")[-1]
                    else:
                        input_val = ""
                base_name = f"{mod_name} ({input_val})"
                
                # Create two columns for split parameters
                high_param_name = f'high {base_name}'
                low_param_name = f'low {base_name}'
                # Create two columns for high/low (t-1) parameters
                prev_high_param_name = f'high {base_name} (t-1)'
                prev_low_param_name = f'low {base_name} (t-1)'

                param_names.extend([high_param_name, low_param_name, prev_high_param_name, prev_low_param_name])

                if 'value' in props:
                    # Get the monitoring result
                    if "monitoringResult" in props:
                        result = props["monitoringResult"]
                        # Map levels for high and low parameters
                        sensor_row[high_param_name] = (
                            2 if 'CRITICAL_HIGH' in result else
                            1 if 'WARNING_HIGH' in result else 0
                        )
                        sensor_row[low_param_name] = (
                            2 if 'CRITICAL_LOW' in result else
                            1 if 'WARNING_LOW' in result else 0
                        )

                        # Get t-30 (t-1) result
                        history_queue = history[base_name]
                        if len(history_queue) >= 30: # if length is 30, t-30 exists
                            t_minus_30_result = history_queue[0]
                            sensor_row[prev_high_param_name] = (
                                2 if 'CRITICAL_HIGH' in t_minus_30_result else
                                1 if 'WARNING_HIGH' in t_minus_30_result else 0
                            )
                            sensor_row[prev_low_param_name] = (
                                2 if 'CRITICAL_LOW' in t_minus_30_result else
                                1 if 'WARNING_LOW' in t_minus_30_result else 0
                            )
                        else:
                            sensor_row[prev_high_param_name] = 0
                            sensor_row[prev_low_param_name] = 0
                        # Append current result to history
                        history_queue.append(result)

                # Store all properties
                for prop_key, prop_val in props.items():
                    column_name = f"{base_name}_{prop_key}"
                    sensor_row[column_name] = prop_val

        # Define the fan status for the current simulation
        if fan_status is None or fan_status == 'on':
            sensor_row['Fan Status'] = 1
        elif fan_status == 'off':
            sensor_row['Fan Status'] = 0

        # Symptom-based anomaly injection
        # 1. Set hidden component = 1 at the malfunction tick
        if anomaly_name is not None and anomaly_tick is not None and tick_num is not None:
            if anomaly_name in ANOMALY_SYMPTOMS:
                comp = ANOMALY_SYMPTOMS[anomaly_name]["component"]
                sensor_row[comp] = int(tick_num >= anomaly_tick)
            # For second_anomaly (e.g., default_leak sets both IHab and HALO)
            if second_anomaly is not None and second_anomaly in ANOMALY_SYMPTOMS:
                comp2 = ANOMALY_SYMPTOMS[second_anomaly]["component"]
                sensor_row[comp2] = int(tick_num >= anomaly_tick)

        # 2. Set each anomaly = 1 only when its hidden component is active
        #    AND ALL expected symptoms meet their threshold.
        #    If component is active but symptoms have decayed, anomaly stays 0
        #    (Unknown Anomaly will catch it later).
        for anom_name, anom_info in ANOMALY_SYMPTOMS.items():
            comp_col = anom_info["component"]
            component_active = sensor_row.get(comp_col, 0) == 1
            if component_active:
                ihab_sensors = []
                for i in anom_info["sensors"]:
                    if i[0].endswith("(IHab)"):
                        ihab_sensors.append(i)

                if fan_status == 'on' or fan_status is None:
                    all_symptoms_met = all(
                        sensor_row.get(sensor, 0) >= threshold
                        for sensor, threshold in anom_info["sensors"]
                    )
                elif fan_status == 'off':
                    all_symptoms_met = all(
                        sensor_row.get(sensor, 0) >= threshold
                        for sensor, threshold in ihab_sensors)

                sensor_row[anom_name] = int(all_symptoms_met)
            else:
                sensor_row.setdefault(anom_name, 0)

        # Ensure all anomaly columns exist with default 0
        for anomaly in anomalies_list:
            sensor_row.setdefault(anomaly, 0)

        # Set group columns based on active anomalies
        for group_name, group_anomalies in ANOMALY_GROUPS.items():
            sensor_row[group_name] = int(any(
                sensor_row.get(a, 0) == 1 for a in group_anomalies
            ))

        # Check whether any known anomalies are present
        no_known_anomalies = all(sensor_row[anomaly] != 1 for anomaly in anomalies_list)
        # Check whether any parameter values are off-nominal
        no_active_params = all(sensor_row.get(param, 0) == 0 for param in param_names)

        if no_known_anomalies and not no_active_params:
            sensor_row['Unknown Anomaly'] = 1
        else:
            sensor_row['Unknown Anomaly'] = 0

        if no_known_anomalies and no_active_params:
            sensor_row['No Anomalies Present'] = 1
        else:
            sensor_row['No Anomalies Present'] = 0

        # Only store if sensor values are found
        if len(sensor_row) > 1: # more than just tick
            rows.append(sensor_row)

    return rows


def run_simulation(server_url, config_path, num_ticks):
    """
    Start a simulation with the given config, advance it, and return the log data.
    
    Args:
        server_url: BioSim server URL
        config_path: Path to the .biosim config file
        num_ticks: Number of ticks to advance the simulation
    
    Returns:
        JSON log data from the simulation
    """
    # Read the config file
    with open(config_path, 'r') as f:
        biosim_xml = f.read()

    # Lock for the start call
    with _start_lock:
        # Submit the XML config and get a simulation ID
        resp = requests.post(
            f'{server_url}/api/simulation/start',
            headers={'Content-Type': 'text/plain'},
            data=biosim_xml
        )
        if not resp.ok:
            raise RuntimeError(f"Failed to start simulation for {config_path}: {resp.status_code} {resp.text}")
        simID = resp.json()['simId']
        print(f"    Started {os.path.basename(config_path)} → simID={simID}")

    # Tick advancement runs outside the lock
    for i in range(num_ticks):
        resp = requests.post(f'{server_url}/api/simulation/{simID}/tick')
        time.sleep(0.02) # small delay to avoid overwhelming the server

    resp = requests.get(f'{server_url}/api/simulation/{simID}/log')
    if not resp.ok:
        raise RuntimeError(f"Failed to get simulation log for {config_path}: {resp.status_code} {resp.text}")

    data = resp.json()
    return data


def run_single_config(config_name, config_info, server_url, num_ticks):
    """
    Run a single simulation config end-to-end: simulate + parse.
    Returns (config_name, rows, elapsed_seconds).
    Thread-safe — no shared mutable state.
    """
    t0 = time.time()
    config_path = os.path.join(CONFIG_DIR, config_name)
    anomaly_name = config_info['anomaly']
    anomaly_tick = config_info['tick']
    fan_status = config_info.get('fan_status', None)
    halo_anomaly = config_info.get('halo_anomaly', None)
    halo_sensors = config_info.get('halo_sensors', None)
    second_anomaly = config_info.get('second_anomaly', None)

    data = run_simulation(server_url, config_path, num_ticks)
    rows = parse_simulation_ticks(data, anomaly_name, anomaly_tick, anomalies,
                                 halo_anomaly=halo_anomaly, halo_sensors=halo_sensors,
                                 second_anomaly=second_anomaly, fan_status=fan_status)
    elapsed = time.time() - t0
    return config_name, rows, elapsed


def get_ordered_bn_columns(all_nodes):
    sensors = ['ppCO2', 'ppO2', 'Humidity', 'Total_Cabin_Pressure']
    locations = ['HALO', 'IHab']
    param_nodes_ordered = []
    for sensor in sensors:
        for loc in locations:
            low = next((n for n in all_nodes if f'low {sensor} ({loc})' in n and '(t-1)' not in n), None)
            high = next((n for n in all_nodes if f'high {sensor} ({loc})' in n and '(t-1)' not in n), None)
            if low: param_nodes_ordered.append(low)
            if high: param_nodes_ordered.append(high)
    anomaly_nodes_ordered = [n for n in anomalies if n in all_nodes]
    hidden_nodes_ordered = [n for n in all_nodes if '[HIDDEN]' in n]
    other_nodes_ordered = [
        n for n in all_nodes if n not in param_nodes_ordered
                                 and n not in anomaly_nodes_ordered
                                 and n not in hidden_nodes_ordered
    ]
    return param_nodes_ordered + anomaly_nodes_ordered + hidden_nodes_ordered + other_nodes_ordered


# Run simulation with threads
def run_all_simulations_threaded(max_workers, num_ticks, server_url=SERVER_URL):
    """
    Run all configs in parallel using ThreadPoolExecutor.
    Returns (all_rows, total_elapsed, per_config_times).
    """
    all_rows = []
    per_config_times = {}

    t_total_start = time.time()

    with ThreadPoolExecutor(max_workers=max_workers) as executor:
        futures = {
            executor.submit(run_single_config, name, info, server_url, num_ticks): name
            for name, info in CONFIG_ANOMALY_MAP.items()
        }

        for future in as_completed(futures):
            config_name = futures[future]
            try:
                name, rows, elapsed = future.result()
                per_config_times[name] = elapsed
                all_rows.extend(rows)
                print(f"  [Thread] {name}: {len(rows)} rows in {elapsed:.2f}s")
            except Exception as e:
                per_config_times[config_name] = -1
                print(f"  [Thread] ERROR {config_name}: {e}")

    total_elapsed = time.time() - t_total_start
    return all_rows, total_elapsed, per_config_times

# Run simulation without threads
def run_all_simulations_sequential(num_ticks, server_url=SERVER_URL):
    """
    Run all configs sequentially (baseline for comparison).
    Returns (all_rows, total_elapsed, per_config_times).
    """
    all_rows = []
    per_config_times = {}

    t_total_start = time.time()

    for config_name, config_info in CONFIG_ANOMALY_MAP.items():
        try:
            name, rows, elapsed = run_single_config(config_name, config_info, server_url, num_ticks)
            per_config_times[name] = elapsed
            all_rows.extend(rows)
            print(f"  [Sequential] {name}: {len(rows)} rows in {elapsed:.2f}s")
        except Exception as e:
            per_config_times[config_name] = -1
            print(f"  [Sequential] ERROR {config_name}: {e}")

    total_elapsed = time.time() - t_total_start
    return all_rows, total_elapsed, per_config_times


# Function for parameter learning and saving the CPDs to a file
def run_parameter_learning(all_rows, output_prefix="threaded"):
    """Run Bayesian Estimator parameter learning on collected simulation data."""
    from pgmpy.estimators import BayesianEstimator as BE

    t0 = time.time()

    df_full = pd.DataFrame(all_rows)
    print(f"\nFull dataset shape: {df_full.shape}")

    # Save DataFrame for parameter learning
    full_filepath = f'biosim_full_{output_prefix}.csv'
    df_full.to_csv(full_filepath, index=False)
    print(f'Saved full biosim dataset to {full_filepath}')

    # Extract relevant columns for parameter learning dataset
    ordered_cols = get_ordered_bn_columns(model.nodes())
    df_training = df_full[[col for col in ordered_cols if col in df_full.columns]]
    print(f'Training dataset shape: {df_training.shape}')

    training_filepath = f'biosim_training_dataset_{output_prefix}.csv'
    df_training.to_csv(training_filepath, index=False)
    print(f'Saved training dataset to {training_filepath}')

    # Create samples from biosim training dataset
    samples = df_training

    new_model = BayesianNetwork(ebunch = model.edges())

    state_names = {}
    for node in new_model.nodes():
        if '[HIDDEN]' in node or node in anomalies or node == 'Fan Status':
            state_names[node] = [0, 1]
        else:
            state_names[node] = [0, 1, 2]

    estimator = BE(new_model, samples, state_names=state_names)

    # If different prior strengths are desired for different anomalies in the network (for example,
    # having greater confidence in a CDRA failure prior than an Unknown Anomaly), a library of node
    # priors can be set up here
    PRIOR_STRENGTH = 5

    def compute_alpha(node, model, state_names):
        """
        Compute the per-node alpha so that the total prior pseudocounts = PRIOR_STRENGTH,
        regardless of the CPD dimensions
        """
        parents = model.get_parents(node)
        # Find the cardinality of the node in question
        k = len(state_names[node])

        if not parents:
            # Root node: CPD is just k states
            return PRIOR_STRENGTH / k
        else:
            # Compute the number of parent combinations for a given child node
            num_parent_combos = prod(len(state_names[p]) for p in parents)
            # Total CPD entries = k * num_parent_combos
           
            # if node == '[HIDDEN] BFS Component' or node == '[HIDDEN] CDRA Failure Component':
            #     # print(f'Alpha for {node}: {PRIOR_STRENGTH / (k * num_parent_combos)}')
            #     return PRIOR_STRENGTH / (2 * k * num_parent_combos)
            # else:
            return PRIOR_STRENGTH / (k * num_parent_combos)
        
    # Build the pseudo_counts dictionary expected by BayesianEstimator
    # Updated to have the correct shape for each specific node
    def build_node_pseudo_counts(node, model, state_names, alpha):
        """
        Build pseudo_counts in the shape pgmpy expects for a given node:
        (k, num_parent_combos) as a list of lists
        """
        parents = model.get_parents(node)
        k = len(state_names[node])

        if not parents:
            num_parent_combos = 1
        else:
            num_parent_combos = prod(len(state_names[p]) for p in parents)

        # Shape: (k, num_parent_combos) — each row is a state, each col is a parent combo
        return [[alpha] * num_parent_combos for _ in range(k)]        

    # Store learned nodes to determine which nodes need to be learned from data
    known_nodes = {cpd.variable for cpd in known_cpds}
    nodes_to_learn = [n for n in new_model.nodes if n not in known_nodes]

    learned_cpds = []
    for node in nodes_to_learn:        
        alpha = compute_alpha(node, new_model, state_names)
        # print(f'alpha: {alpha}')
        node_pseudo_counts = build_node_pseudo_counts(node, new_model, state_names, alpha)

        # Use .estimate_cpd method instead of .get_parameters as we are learning only a subset of the network's CPDs
        cpd = estimator.estimate_cpd(
            node,
            prior_type='dirichlet',
            pseudo_counts=node_pseudo_counts) # can update pseudo_counts dictionary if priors too uniform
        learned_cpds.append(cpd)

    for cpd in learned_cpds:
        print(cpd)

    cpds_filepath = os.path.join(current_dir, f'all_cpds_{output_prefix}.txt')

    with open(cpds_filepath, 'w') as f:
        f.write("=== Learned CPDs ===\n\n")
        for cpd in learned_cpds:
            f.write(str(cpd))
            f.write('\n\n')
            # f.write(f"Variable: {cpd.variable}\n")
            # f.write(f"Parents: {cpd.variables[1:]}\n")
            # f.write(f"Values:\n{cpd.get_values()}\n\n")
        f.write("=== Known CPDs ===\n\n")
        for cpd in known_cpds:
            f.write(str(cpd))
            f.write('\n\n')
            # f.write(f"Variable: {cpd.variable}\n")
            # f.write(f"Parents: {cpd.variables[1:]}\n")
            # f.write(f"Values:\n{cpd.get_values()}\n\n")
    print(f'Saved CPDs to {cpds_filepath}')

    # Add learned CPDs to known deterministic CPDs previously defined
    new_model.add_cpds(*learned_cpds, *known_cpds)
    print('Model valid:', new_model.check_model())

    be_elapsed = time.time() - t0
    print(f'Parameter learning took {be_elapsed:.2f}s')
    return be_elapsed


def start_biosim_server():
    """Start the BioSim Java server and wait for it to be ready."""
    jar_path = os.path.join(_mars_repos_dir, 'biosim', 'target', 'biosim-2.0.0-jar-with-dependencies.jar')
    proc = subprocess.Popen(['java', '-jar', jar_path, '--writeTicks'])
    print('Starting BioSim server...')

    for attempt in range(30):
        try:
            resp = requests.get(f'{SERVER_URL}/api/simulation', timeout=2)
            if resp.ok:
                print(f'BioSim server ready after {attempt + 1}s')
                return proc
        except requests.ConnectionError:
            pass
        time.sleep(1)

    print('Warning: BioSim server may not be ready, proceeding anyway...')
    return proc


def stop_biosim_server(proc):
    """Terminate the BioSim server."""
    if proc:
        proc.terminate()
        proc.wait(timeout=10)
        print('BioSim server stopped.')


# Testing: run tests across different thread counts and tick counts
def run_testing(worker_counts, tick_counts):
    """
    Run simulations across all combinations of worker_counts and tick_counts.
    Collects timing data and prints a summary table.
    """
    results = []  # list of dicts: {workers, ticks, total_time, sim_time, be_time, rows}

    for num_ticks in tick_counts:
        for num_workers in worker_counts:
            label = f"sequential" if num_workers == 1 else f"{num_workers} threads"
            print(f"\n{'='*70}")
            print(f"  TESTING: {label}, {num_ticks} ticks")
            print(f"{'='*70}")

            server_proc = start_biosim_server()

            try:
                t_run_start = time.time()

                if num_workers == 1:
                    all_rows, sim_time, per_config = run_all_simulations_sequential(num_ticks)
                else:
                    all_rows, sim_time, per_config = run_all_simulations_threaded(num_workers, num_ticks)

                num_rows = len(all_rows)
                print(f"\n  Simulation phase: {sim_time:.2f}s, {num_rows} rows collected")

                # Run BE parameter learning
                if num_rows > 0:
                    be_time = run_parameter_learning(all_rows, output_prefix=f"w{num_workers}_t{num_ticks}")
                else:
                    be_time = 0.0
                    print("  Skipping BE learning (no data)")

                total_time = time.time() - t_run_start

                results.append({
                    'workers': num_workers,
                    'ticks': num_ticks,
                    'sim_time': sim_time,
                    'be_time': be_time,
                    'total_time': total_time,
                    'rows': num_rows,
                    'configs': len(CONFIG_ANOMALY_MAP),
                })

            except Exception as e:
                print(f"  TESTING ERROR: {e}")
                results.append({
                    'workers': num_workers,
                    'ticks': num_ticks,
                    'sim_time': -1,
                    'be_time': -1,
                    'total_time': -1,
                    'rows': 0,
                    'configs': len(CONFIG_ANOMALY_MAP),
                })
            finally:
                stop_biosim_server(server_proc)
                time.sleep(3) # give port time to free up

    # Print summary table
    print(f"\n\n{'='*90}")
    print(f"  TESTING RESULTS SUMMARY")
    print(f"{'='*90}")
    print(f"{'Workers':>8} | {'Ticks':>6} | {'Sim Time':>10} | {'BE Time':>10} | {'Total Time':>11} | {'Rows':>7} | {'Speedup':>8}")
    print(f"{'-'*8}-+-{'-'*6}-+-{'-'*10}-+-{'-'*10}-+-{'-'*11}-+-{'-'*7}-+-{'-'*8}")

    # Sequential times for speedup calculation
    baseline_times = {}
    for r in results:
        if r['workers'] == 1 and r['sim_time'] > 0:
            baseline_times[r['ticks']] = r['sim_time']

    for r in results:
        sim_str = f"{r['sim_time']:.2f}s" if r['sim_time'] >= 0 else "ERROR"
        be_str = f"{r['be_time']:.2f}s" if r['be_time'] >= 0 else "ERROR"
        total_str = f"{r['total_time']:.2f}s" if r['total_time'] >= 0 else "ERROR"

        baseline = baseline_times.get(r['ticks'], None)
        if baseline and r['sim_time'] > 0:
            speedup = f"{baseline / r['sim_time']:.2f}x"
        elif r['workers'] == 1 and r['sim_time'] > 0:
            speedup = "1.00x"
        else:
            speedup = "N/A"

        print(f"{r['workers']:>8} | {r['ticks']:>6} | {sim_str:>10} | {be_str:>10} | {total_str:>11} | {r['rows']:>7} | {speedup:>8}")

    print(f"{'='*90}")

    # Save results to CSV
    results_df = pd.DataFrame(results)
    results_filepath = 'testing_results.csv'
    results_df.to_csv(results_filepath, index=False)
    print(f"\nTesting results saved to {results_filepath}")

    return results


# Main function to run the simulation given thread count and tick count
def run_single(num_workers, num_ticks):
    """Run a single simulation pass with the given thread count and tick count."""
    server_proc = start_biosim_server()

    try:
        if num_workers == 1:
            all_rows, sim_time, per_config = run_all_simulations_sequential(num_ticks)
        else:
            all_rows, sim_time, per_config = run_all_simulations_threaded(num_workers, num_ticks)

        print(f"\n{'='*60}")
        print(f"  Simulation completed: {sim_time:.2f}s, {len(all_rows)} rows")
        print(f"{'='*60}")

        if len(all_rows) > 0:
            be_time = run_parameter_learning(all_rows, output_prefix=f"w{num_workers}_t{num_ticks}")
            print(f"\n  Total time: sim={sim_time:.2f}s + learning={be_time:.2f}s = {sim_time + be_time:.2f}s")
        elif len(all_rows) == 0:
            print("\n  No rows collected — skipping parameter learning")

    finally:
        stop_biosim_server(server_proc)

def main():
    parser = argparse.ArgumentParser(
        description="Threaded BioSim simulation runner with testing"
    )
    parser.add_argument('--workers', type=int, default=4,
                        help='Number of threads for simulation (default: 4)')
    parser.add_argument('--ticks', type=int, default=1000,
                        help='Number of simulation ticks (default: 1000)')
    parser.add_argument('--testing', action='store_true',
                        help='Run a full simulation across different thread and tick combinations')
    parser.add_argument('--testing-workers', type=str, default='1,2,4,6,8,10,12,14,16',
                        help='Comma-separated thread counts (default: 1,2,4,6,8,10,12,14,16)')
    parser.add_argument('--testing-ticks', type=str, default='500,1000',
                        help='Comma-separated tick counts (default: 500,1000)')


    args = parser.parse_args()

    if args.testing:
        worker_counts = [int(x.strip()) for x in args.testing_workers.split(',')]
        tick_counts = [int(x.strip()) for x in args.testing_ticks.split(',')]
        print(f"Running testing: workers={worker_counts}, ticks={tick_counts}")
        print(f"Total runs: {len(worker_counts) * len(tick_counts)}")
        run_testing(worker_counts, tick_counts)
    else:
        print(f"Running with {args.workers} worker(s), {args.ticks} ticks")
        run_single(args.workers, args.ticks)


if __name__ == '__main__':
    main()
