# learn_probabilities.py
# Author: Joshua Elston
# Last Edited: 2/11/2026

# This script is used to create simulation runs of the IHab/HALO Gateway
# environment using the Biosim configuration files generated by TRACLabs.
# With the reduced subset of anomaly scenarios being modeled, the script
# then looks to perform parameter learning to inform the probabilities
# within the Bayesian network CPDs.

import os, json, subprocess, requests, time
import pandas as pd

from pgmpy.utils import get_example_model
print(get_example_model(model='alarm'))

from pgmpy.models import BayesianNetwork
from pgmpy.factors.discrete import TabularCPD
from reduced_network_structure import reduced_network
from reduced_prior_probabilities import reduced_prior_probabilities
from reduced_add_cpds import add_cpds

current_dir = os.path.dirname(os.path.abspath(__file__))
reduced_split_probability_dict = os.path.join(current_dir, "reduced_split_probabilities_dict.json")
reduced_hidden_probabilities_dict = os.path.join(current_dir, "reduced_hidden_probabilities_dict.json")
with open(reduced_split_probability_dict, "r") as file:
    reduced_split_probability_dict = json.load(file)
with open(reduced_hidden_probabilities_dict, "r") as file:
    reduced_hidden_probabilities_dict = json.load(file)

# Define the cardinality of each anomaly as 2, where 0 represents the anomaly not being present (False) and 1 represents the anomaly being present (True)
anomaly_cardinality = 2

# Create the Bayesian Network
model = BayesianNetwork(reduced_network)
print(model)

# NOTE: Given that the anomalies are no longer the top layer in the network, they
# do not have prior probabilities defined given their subgroup parents

prior_cpds_dict = {}

# # From the prior probabilities, add CPDs for the anomalies
# for anomaly, prior_probability in reduced_prior_probabilities.items():
#     model.add_cpds(TabularCPD(
#                             variable = anomaly, 
#                             variable_card = anomaly_cardinality, 
#                             values = [[1 - prior_probability], [prior_probability]] # ordered as [False, True]
#                             ))
#     prior_cpds_dict[anomaly] = {'False': 1 - prior_probability, 'True': prior_probability}

# # Add the CPDs for the parameters conditioned on multiple anomalies
# add_cpds(model, reduced_split_probability_dict, reduced_hidden_probabilities_dict, anomaly_cardinality)

print('you are here---')

# Start Biosim simulation by calling java file (avoiding call to bash with 'bin')
jar_path = "mars_repos/biosim/target/biosim-2.0.0-jar-with-dependencies.jar"  # adjust as needed
server_proc = subprocess.Popen(['java', '-jar', jar_path, '--writeTicks'])
print('Starting Biosim server...')

# Wait for server to start listening on port 8009
time.sleep(5)

# Parameters
SERVER_URL = 'http://localhost:8009'
# Set the configuration file to use for the current simulation
# Might want to see if there's a way to switch to different config files or restart
# a config for multiple runs
CONFIG_PATH = 'mars_repos/biosim-daphne/configuration/default.biosim'
# Adjust if different simulation length desired <-- currently long enough to see injected
# failure and conditions degrade, but not long enough time scale for conditions to restore
NUM_TICKS = 500 

# 1. Start Simulation
with open(CONFIG_PATH, 'r') as f:
    biosim_xml = f.read()

# Submit the XML config and get a simulation ID
resp = requests.post(
    f'{SERVER_URL}/api/simulation/start',
    headers={'Content-Type': 'text/plain'},
    data=biosim_xml
)
if not resp.ok:
    raise RuntimeError(f"Failed to start simulation: {resp.status_code} {resp.text}")
simID = resp.json()['simId']
print(f"Started BioSim simulation. Got simID: {simID}")

# 2. Advance Simulation
for i in range(NUM_TICKS):
    resp = requests.post(f'{SERVER_URL}/api/simulation/{simID}/tick')
    time.sleep(0.02)  # small delay to avoid overwhelming the server
print(f"Advanced simulation {NUM_TICKS} ticks.")

# 3. Fetch Run Log (all tick snapshots) <-- only works if tick logging is enabled with --writeTicks
resp = requests.get(f'{SERVER_URL}/api/simulation/{simID}/log')
if not resp.ok:
    raise RuntimeError(f"Failed to get simulation log: {resp.status_code} {resp.text}")

data = resp.json()
print("Downloaded log with", len(data.get('ticks', [])), "ticks.")

# 4. Parse tick snapshots into DataFrame
rows = []

anomalies = ["Biological Filter Saturation (IHab)", "Biological Filter Saturation (HALO)",
             "CDRA Failure (IHab)", "CDRA Failure (HALO)",
             "Emergency O2 System Maintenance (IHab)","Emergency O2 System Maintenance (HALO)",
             "Excess CO2 in Cabin (IHab)","Excess CO2 in Cabin (HALO)",
             "Loss of Pressure (IHab)", "Loss of Pressure (HALO)"]

from collections import defaultdict, deque
history = defaultdict(lambda: deque(maxlen=30)) # changed from maxlen = 31, may need to change back

for idx, tick in enumerate(data.get('ticks', [])):
    tick_num = tick.get('tick', idx)
    modules_state = tick.get('modules', {})
    sensor_row = {'tick': tick_num}

    param_names = []
    for mod_name, mod in modules_state.items():
        module_type = mod.get('moduleType', '')
        if "Sensor" in module_type:
            props = mod.get('properties', {})
            input_val = mod.get('input')
            if input_val is None:
                if "_" in mod_name:
                    input_val = mod_name.split("_")[-1]
                else:
                    input_val = ""
            base_name = f"{mod_name} ({input_val})"

            # Create two columns for split parameters
            high_param_name = f'high {base_name}'
            low_param_name = f'low {base_name}'
            # Create two columns for high/low (t-1) parameters
            prev_high_param_name = f'high {base_name} (t-1)'
            prev_low_param_name = f'low {base_name} (t-1)'

            param_names.extend([high_param_name, low_param_name, prev_high_param_name, prev_low_param_name])

            if 'value' in props:
                sensor_value = props['value']

                # Get the monitoring result
                if "monitoringResult" in props:
                    result = props["monitoringResult"]
                    # Map levels for high and low parameters
                    sensor_row[high_param_name] = (
                        2 if 'CRITICAL_HIGH' in result else
                        1 if 'WARNING_HIGH' in result else 0
                    )
                    sensor_row[low_param_name] = (
                        2 if 'CRITICAL_LOW' in result else
                        1 if 'WARNING_LOW' in result else 0
                    )

                    # Get t-30 (t-1) result
                    history_queue = history[base_name]
                    if len(history_queue) >= 30: # if length is 30, t-30 exists
                        t_minus_30_result = history_queue[0]
                        sensor_row[prev_high_param_name] = (
                            2 if 'CRITICAL_HIGH' in t_minus_30_result else
                            1 if 'WARNING_HIGH' in t_minus_30_result else 0 
                        )
                        sensor_row[prev_low_param_name] = (
                            2 if 'CRITICAL_LOW' in t_minus_30_result else
                            1 if 'WARNING_LOW' in t_minus_30_result else 0                           
                        )
                    else:
                        sensor_row[prev_high_param_name] = 0
                        sensor_row[prev_low_param_name] = 0
                    # Append current result to history
                    history_queue.append(result)

            # Store all properties
            for prop_key, prop_val in props.items():
                column_name = f"{base_name}_{prop_key}"
                sensor_row[column_name] = prop_val

    # Inject anomalies following tick logic
    if tick_num is not None:
        sensor_row['CDRA Failure (IHab)'] = int(tick_num >= 200)
    else:
        sensor_row['CDRA Failure (IHab)'] = 0
    for anomaly in anomalies:
        sensor_row.setdefault(anomaly, 0)
   
    # Check whether any known anomalies are present
    no_known_anomalies = all(sensor_row[anomaly] != 1 for anomaly in anomalies)
    # Check whether any parameter values are off-nominal
    no_active_params = all(sensor_row[param] == 0 for param in param_names)

    if no_known_anomalies and not no_active_params:
        sensor_row['Unknown Anomaly'] = 1
    else:
        sensor_row['Unknown Anomaly'] = 0

    if no_known_anomalies and no_active_params:
        sensor_row['No Anomalies Present'] = 1
    else:
        sensor_row['No Anomalies Present'] = 0

    # Only store if sensor values are found
    if len(sensor_row) > 1:  # more than just tick
        rows.append(sensor_row)

def get_ordered_bn_columns(all_nodes):
    sensors = ['ppCO2', 'ppO2', 'Humidity', 'Total_Cabin_Pressure']
    locations = ['HALO', 'IHab']
    # Parameter nodes
    param_nodes_ordered = []
    for sensor in sensors:
        for loc in locations:
            low = next((n for n in all_nodes if f'low {sensor} ({loc})' in n and '(t-1)' not in n), None)
            high = next((n for n in all_nodes if f'high {sensor} ({loc})' in n and '(t-1)' not in n), None)
            if low: param_nodes_ordered.append(low)
            if high: param_nodes_ordered.append(high)
    anomaly_nodes_ordered = [n for n in anomalies if n in all_nodes]
    other_nodes_ordered = [
        n for n in all_nodes if n not in param_nodes_ordered
                                 and n not in anomaly_nodes_ordered
                                 and not '[HIDDEN]' in n
    ]
    return param_nodes_ordered + anomaly_nodes_ordered + other_nodes_ordered

df_full = pd.DataFrame(rows)
print("Full dataset shape:", df_full.shape)
print(df_full.head())

# 5. Save DataFrame for parameter learning
full_filepath = 'biosim_full.csv'
df_full.to_csv(full_filepath, index=False)
print('Saved full biosim dataset to', full_filepath)

# After simulation, terminate server
server_proc.terminate()

# node_names = set(model.nodes()) # includes parameters, anomalies, and hidden parameters
# print(node_names)

# Extract relevant columns for parameter learning dataset
ordered_cols = get_ordered_bn_columns(model.nodes())
df_training = df_full[[col for col in ordered_cols if col in df_full.columns]]
print('Training dataset shape', df_training.shape)
print(df_training.head())
training_filepath = 'biosim_training_dataset.csv'
df_training.to_csv(training_filepath, index=False)
print('Saved training dataset to', training_filepath)

# Create samples from biosim training dataset
samples = df_training.iloc[[30, 150, 250, 350, 450]]
# samples = df_training
print(samples.head())

# Create blank model from which to learn new parameter probabilities
new_model = BayesianNetwork(ebunch=model.edges())

# Add hidden evidence as latent variables
latent_variables = []
for edge in model.edges:
    for node in edge:
        if '[HIDDEN]' in node:
            # print('Hidden parameter found at', node)
            if node not in latent_variables:
                latent_variables.append(node)
# print(latent_variables)

# Drop latent variables (if any) for Expectation Maximization input
samples_latent = samples.drop(latent_variables, errors='ignore')
# Build model using latents
model_latent = BayesianNetwork(model.edges(), latents=set(latent_variables))

from pgmpy.estimators import ExpectationMaximization as EM
em_est = EM(model_latent, data=samples_latent)
learned_cpds = em_est.get_parameters()
for cpd in learned_cpds:
    print(cpd)
model_latent.add_cpds(*learned_cpds)